#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# =============================================================================
# Created Syst: macOS Monterey 12.4 (21F79) Kernel: Darwin 21.5.0
# Created Plat: Python 3.10.5 ('v3.10.5:f377153967', 'Jun  6 2022 12:36:10')
# Created By  : Jeromie Kirchoff
# Created Date: Mon Jun 13 03:22:59 2022 CDT
# Last ModDate: Tue Jul 12 16:14:33 2022 CDT
# =============================================================================
# Notes: Generate a Random Animal/Fish/Insect/Reptile Name.
# =============================================================================

from random import choice

animals = [
    "Aardvark",
    "Aardwolf",
    "Abyssinian",
    "Addax",
    "Adelie penguin",
    "Adélie penguin",
    "Aesculapian snake",
    "Affenpinscher",
    "Afghan hound",
    "Africa openbill",
    "African buffalo",
    "African bullfrog",
    "African bush elephant",
    "African bushback",
    "African civet",
    "African clawed frog",
    "African crowned crane",
    "African elephant",
    "African forest elephant",
    "African grey parrot",
    "African lion",
    "African lions",
    "African palm civet",
    "African penguin",
    "African spurred tortoise",
    "African tree frog",
    "African tree toad",
    "African wild dog",
    "Africanized bees",
    "Agama lizard",
    "Agouti",
    "Aidi",
    "Ainu",
    "Ainu dog",
    "Airedale terrier",
    "Airedoodle",
    "Akbash",
    "Akita",
    "Akita shepherd",
    "Alabai",
    "Alaskan husky",
    "Alaskan klee kai",
    "Alaskan malamute",
    "Alaskan pollock",
    "Alaskan shepherd",
    "Albacore",
    "Albacore tuna",
    "Albatross",
    "Aldabra giant tortoise",
    "Allen's swamp monkeys",
    "Alligator",
    "Alligator gar",
    "Allis shad",
    "Allosaurus",
    "Alpaca",
    "Alpine dachsbracke",
    "Alpine goat",
    "Alpine ibex",
    "Alusky",
    "Amazon dolphin",
    "Amazon parrot",
    "Amazon river dolphin",
    "Amazon river dolphin (pink dolphin)",
    "Amazonian manatee",
    "Amberjack",
    "Ambrosia beetle",
    "American alligator",
    "American alsatian",
    "American badger",
    "American bison",
    "American bulldog",
    "American cocker spaniel",
    "American cockroach",
    "American coonhound",
    "American crow",
    "American dog tick",
    "American eskimo dog",
    "American foxhound",
    "American hairless terrier",
    "American kestrel",
    "American leopard hound",
    "American oystercatcher",
    "American pit bull terrier",
    "American pygmy goat",
    "American robin",
    "American staffordshire terrier",
    "American toad",
    "American water spaniel",
    "Amur leopard",
    "An american badger",
    "An atlantic wolffish",
    "Anaconda",
    "Anaconda snake",
    "Anatolian shepherd dog",
    "Anchovies",
    "Anchovy",
    "Andean condor",
    "Angelfish",
    "Anglerfish",
    "Angora ferret",
    "Angora goat",
    "Anhinga",
    "Anole",
    "Anole lizard",
    "Ant",
    "Antarctic scale worm",
    "Anteater",
    "Antelope",
    "Ants",
    "Aoudad",
    "Apallousa horse",
    "Ape",
    "Appenzeller dog",
    "Apple head chihuahua",
    "Aquatic warbler",
    "Arab baboon",
    "Arabian cobra",
    "Arabian horse",
    "Arafura file snake",
    "Arapaima",
    "Archaeotherium",
    "Archelon turtle",
    "Arctic fox",
    "Arctic hare",
    "Arctic tern",
    "Arctic wolf",
    "Arctic wolfarmadillo",
    "Arctodus",
    "Arctotherium",
    "Arcus pheasant",
    "Argus",
    "Arizona bark scorpion",
    "Arizona black rattlesnake",
    "Arizona coral snake",
    "Armadillo",
    "Armadillo lizard",
    "Armyworm",
    "Arowana",
    "Arthropod",
    "Aruba rattlesnake",
    "Asian arowana",
    "Asian cockroach",
    "Asian elephant",
    "Asian giant hornet",
    "Asian lion",
    "Asian palm civet",
    "Asian vine snake",
    "Asiatic black bear",
    "Asiatic wild ram",
    "Asp",
    "Assassin bug",
    "Atlantic puffin",
    "Atlantic salmon",
    "Atlantic spotted dolphins",
    "Atlas beetle",
    "Atlas moth",
    "Audubon's shearwater",
    "Auk",
    "Auk bird",
    "Aurochs",
    "Aussiedoodle",
    "Aussiedor",
    "Australasian grebe",
    "Australian bulldog",
    "Australian cattle dog",
    "Australian cockroach",
    "Australian dingo",
    "Australian flathead perch",
    "Australian gecko",
    "Australian kelpie dog",
    "Australian labradoodle",
    "Australian mist",
    "Australian pelican",
    "Australian retriever",
    "Australian shepherd",
    "Australian swiftlet",
    "Australian terrier",
    "Australopithecus",
    "Avocet",
    "Axis deer",
    "Axolotl",
    "Aye aye",
    "Aye-aye",
    "Babirusa",
    "Baboon",
    "Bactrian camel",
    "Bactrian camels",
    "Badger",
    "Baiji",
    "Baird's rat snake",
    "Bald eagle",
    "Baldpate",
    "Baleen whale",
    "Balinese",
    "Balkan lynx",
    "Ball python",
    "Banana ball python",
    "Banana eel",
    "Banana spider",
    "Banded krait",
    "Banded palm civet",
    "Banded water snake",
    "Bandicoot",
    "Banjo catfish",
    "Bank vole",
    "Bar jack",
    "Barb",
    "Barbary ape",
    "Barbet",
    "Barbirusa",
    "Barn owl",
    "Barn swallow",
    "Barnacle",
    "Barracuda",
    "Barramundi fish",
    "Barred owl",
    "Basenji dog",
    "Basilisk",
    "Basilisk lizard",
    "Basilosaurus",
    "Basking shark",
    "Bass",
    "Bassador",
    "Basset fauve de bretagne",
    "Basset hound",
    "Bassetoodle",
    "Bat",
    "Batfish",
    "Bavarian mountain hound",
    "Baya",
    "Bea-tzu",
    "Beabull",
    "Beagador",
    "Beagle",
    "Beagle shepherd",
    "Beaglier",
    "Beago",
    "Bean goose",
    "Bear",
    "Bearded collie",
    "Bearded dragon",
    "Bearded vulture",
    "Beaski",
    "Beauceron",
    "Beauty rat snake",
    "Beaver",
    "Bed bugs",
    "Bedlington terrier",
    "Bee",
    "Bee eaters",
    "Beefalo",
    "Bees",
    "Beetle",
    "Beisa oryx",
    "Belgian shepherd",
    "Belgian tervuren",
    "Bellbird",
    "Beluga sturgeon",
    "Beluga whale",
    "Bengal tiger",
    "Bengal tigers1083px-hm_orange_m_sarawut",
    "Bergamasco",
    "Berger picard",
    "Bernedoodle",
    "Bernese mountain dog",
    "Bernese shepherd",
    "Betta",
    "Betta fish (siamese fighting fish)",
    "Bichir",
    "Bichon frise",
    "Bichpoo",
    "Biewer terrier",
    "Big eyed squirrel fish",
    "Bigfin reef squid",
    "Bigfin squid",
    "Bighorn sheep",
    "Bilby",
    "Binturong",
    "Bird",
    "Bird of paradise",
    "Birdaustralasian grebe",
    "Birds of paradise",
    "Birman",
    "Biscuit beetle",
    "Bison",
    "Bisonblack caiman",
    "Black and tan coonhound",
    "Black angus",
    "Black bear",
    "Black bird",
    "Black buck",
    "Black caimans",
    "Black capped squirrel monkeys",
    "Black dolphin",
    "Black footed ferret",
    "Black house spider",
    "Black jaguar",
    "Black mamba",
    "Black mamba snakes",
    "Black marlin",
    "Black molly",
    "Black necked stilt",
    "Black racer",
    "Black rail",
    "Black rat",
    "Black rat snake",
    "Black rhino",
    "Black rhinoceros",
    "Black rhinocerous",
    "Black russian terrier",
    "Black sole",
    "Black swan",
    "Black swift",
    "Black wasp",
    "Black widow spider",
    "Black-capped chickadee",
    "Black-footed ferret",
    "Black-headed gull",
    "Blackbird",
    "Blackpoll warbler",
    "Blacktip reef shark",
    "Blacktip shark",
    "Blacktip sharkblister beetle",
    "Bladefin basslet",
    "Blanket octopus",
    "Blesbok",
    "Blind snake",
    "Blister beetle",
    "Blobfish",
    "Blood pheasant",
    "Blood python",
    "Bloodhound",
    "Bloohounds",
    "Blowfish",
    "Blue and yellow macaw",
    "Blue belly lizard",
    "Blue bull (nilgai)",
    "Blue catfish",
    "Blue duck",
    "Blue eyed pleco",
    "Blue footed booby",
    "Blue gray gnatcatcher",
    "Blue grosbeak",
    "Blue iguana",
    "Blue jay",
    "Blue lacy dog",
    "Blue marlin",
    "Blue picardy spaniel",
    "Blue racer",
    "Blue ringed octopus",
    "Blue runner",
    "Blue shark",
    "Blue tit",
    "Blue tongue skink",
    "Blue whale",
    "Blue-footed booby bird",
    "Blue-ringed octopus",
    "Bluebird",
    "Bluefin tuna",
    "Bluegill",
    "Bluejay",
    "Bluetick coonhound",
    "Boa constricter",
    "Boa constrictor",
    "Boa constrictor snake",
    "Boas",
    "Boatbill heron",
    "Bobacs",
    "Bobcat",
    "Bobolink",
    "Bobwhite quail",
    "Boggle",
    "Boglen terrier",
    "Boiga",
    "Bolivian anaconda",
    "Bolognese dog",
    "Bombay",
    "Bonefish",
    "Bongo",
    "Bonito",
    "Bonito fish",
    "Bonnethead shark",
    "Bonobo",
    "Booby",
    "Booby bird",
    "Boomslang",
    "Borador",
    "Border collie",
    "Border terrier",
    "Bordoodle",
    "Borkie",
    "Bornean orang-utan",
    "Bornean orangutan",
    "Borneo elephant",
    "Boston terrier",
    "Bottle nosed dolphin",
    "Bottlenose dolphin",
    "Bottlenose dolphins",
    "Bouvier des flandres",
    "Bowfin",
    "Bowhead whale",
    "Box tree moth",
    "Box turtle",
    "Boxador",
    "Boxer dog",
    "Boxerdoodle",
    "Boxfish",
    "Boxsky",
    "Boxweiler",
    "Boykin spaniel",
    "Brachiosaurus",
    "Brahminy blindsnake",
    "Brandling worms",
    "Brant",
    "Brazilian terrier",
    "Brazilian wandering spiderbritish mice types",
    "Bream",
    "British micebritish moles",
    "British moles",
    "British timber",
    "British water vole",
    "British wild cats",
    "Brittany",
    "Broad-snouted caimans",
    "Brook trout",
    "Brookesia micra",
    "Brown bear",
    "Brown dog tick",
    "Brown hyena",
    "Brown jay",
    "Brown pelican",
    "Brown recluse",
    "Brown recluse spider",
    "Brown snake",
    "Brown trout",
    "Brown water snake",
    "Brown-banded cockroach",
    "Brug",
    "Brussels griffon",
    "Brydes whale",
    "Budgerigar",
    "Budgie",
    "Buffalo",
    "Buffalo fish",
    "Bufflehead",
    "Bull mastiff",
    "Bull shark",
    "Bull terrier",
    "Bull trout",
    "Bulldog",
    "Bullfrog",
    "Bullhead",
    "Bullmastiff",
    "Bullsnake",
    "Bumble bee",
    "Bumble bees",
    "Bumblebee",
    "Bunting",
    "Buntings",
    "Burmese",
    "Burmese python",
    "Burrowing frog",
    "Burrowing owl",
    "Burying beetle",
    "Bush baby",
    "Bush dog",
    "Bush viper",
    "Bushmaster",
    "Bushmaster snake",
    "Butter fish",
    "Butterflies",
    "Butterfly",
    "Butterfly fish",
    "C. elegans",
    "Cabbage moth",
    "Cacique",
    "Cactus moth",
    "Cactus mouse",
    "Caecilian",
    "Caiman",
    "Caiman lizard",
    "Cairn terrier",
    "California condor",
    "California kingsnake",
    "California quail",
    "Camel",
    "Camel cricket",
    "Camel cricketcamel-spider-2",
    "Camel crickets",
    "Camel spider",
    "Camels",
    "Campbell's dwarf hamster",
    "Canaan dog",
    "Canada goose",
    "Canada lynx",
    "Canada warbler",
    "Canadian eskimo dog",
    "Canadian geese",
    "Canadian horse",
    "Canary",
    "Cane corso",
    "Cane toad",
    "Cantil",
    "Canvasback",
    "Cape gannet birdcapercaillie bird",
    "Cape lion",
    "Capercaillie",
    "Capuchin",
    "Capuchin monkeys",
    "Capybara",
    "Caracal",
    "Caracara bird",
    "Cardinal birds",
    "Caribbean reef sharkcaribou",
    "Caribou",
    "Caribou (reindeer)cassowary-2",
    "Carolina dog",
    "Carolina parakeet",
    "Carolina parakeets",
    "Carp",
    "Carpenter ant",
    "Carpet python",
    "Carpet viper",
    "Cascabel",
    "Cashmere goat",
    "Cassowary",
    "Cat",
    "Cat & kitten",
    "Cat & mouse",
    "Cat shark",
    "Cat snake",
    "Cat-eyed snake",
    "Catahoula leopard",
    "Catalan sheepdog",
    "Catbird",
    "Caterpillar",
    "Catfish",
    "Cats",
    "Cava tzu",
    "Cavador",
    "Cavalier king charles spaniel",
    "Cavapoo",
    "Cave bear",
    "Cave lion",
    "Cecropia moth",
    "Centipede",
    "Central ranges taipan",
    "Cesky fousek",
    "Cesky terrier",
    "Chachalaca",
    "Chameleon",
    "Chamois",
    "Channel catfish",
    "Chartreux",
    "Cheagle",
    "Checkered garter snake",
    "Cheetah",
    "Cheetahchicaree",
    "Chesapeake bay retriever",
    "Chick & egg",
    "Chickadee",
    "Chickaree",
    "Chicken",
    "Chicken snake",
    "Chickens",
    "Chihuahua",
    "Chimaera",
    "Chimpanzee",
    "Chinchilla",
    "Chinese alligator",
    "Chinese cobra",
    "Chinese crested dog",
    "Chinese geese",
    "Chinese hamsters",
    "Chinese paddlefish",
    "Chinese shar-pei",
    "Chinook",
    "Chinook salmon",
    "Chinstrap penguin",
    "Chipmunk",
    "Chipoo",
    "Chipping sparrow",
    "Chiweenie",
    "Chorkie",
    "Chow chow",
    "Chow shepherd",
    "Christmas beetle",
    "Christmas island red crab",
    "Chukar",
    "Cicada",
    "Cicada killer wasps",
    "Cicadas",
    "Cichlid",
    "Cinereous vulture",
    "Cinnamon ferret",
    "Cinnamon teal",
    "Clams",
    "Click beetle",
    "Climbing frog",
    "Clouded leopard",
    "Clown fish",
    "Clownfish",
    "Clumber spaniel",
    "Clydesdale",
    "Coachwhip snake",
    "Coastal taipan",
    "Coati",
    "Cobia",
    "Cobia fish",
    "Cobra",
    "Cobras",
    "Cockalier",
    "Cockapoo",
    "Cockatiel",
    "Cockatoo",
    "Cocker spaniel",
    "Cockroach",
    "Cod",
    "Codfish",
    "Codling moth",
    "Coelacanth",
    "Coho salmon",
    "Coley",
    "Collared peccary",
    "Collett's snake",
    "Collie",
    "Colossal squid",
    "Commerson dolphin",
    "Common buzzard",
    "Common dolphin",
    "Common european adder",
    "Common european bat",
    "Common frog",
    "Common furniture beetle",
    "Common hippopotamus",
    "Common house spider",
    "Common kingfisher",
    "Common lizard",
    "Common loon",
    "Common mackerel",
    "Common newt",
    "Common octopus",
    "Common palm civet",
    "Common raven",
    "Common seal",
    "Common toad",
    "Common wasps",
    "Cone snail",
    "Conger",
    "Conger eel",
    "Congo snake",
    "Cookiecutter shark",
    "Cooper's hawk",
    "Cooper’s hawk",
    "Coot",
    "Copepods",
    "Copperhead",
    "Copperhead snakes",
    "Coral",
    "Coral snake",
    "Corgidor",
    "Corgipoo",
    "Corkie",
    "Corman shepherd",
    "Cormorant",
    "Corn rex cat (cornish rex)",
    "Corn snake",
    "Corncrakecottonmouth snakes",
    "Corsac",
    "Cory catfish",
    "Coton de tulear",
    "Cotton-top tamarin",
    "Cottonmouth",
    "Cottonmouth snakes",
    "Cottontail",
    "Cottontop tamarin",
    "Cougar",
    "Cow",
    "Cows",
    "Coyote",
    "Crab",
    "Crab plover",
    "Crab spider",
    "Crab-eating macaque",
    "Crab-eating opossum",
    "Crabeater seal",
    "Crabs",
    "Crake",
    "Crane",
    "Crappie fish",
    "Crested eagle",
    "Crested gecko",
    "Crested penguin",
    "Crested pigeon",
    "Crested porcupine",
    "Cricket",
    "Criss-cross fish & butterfly fish",
    "Crocodile",
    "Crocodile skink",
    "Cross fox",
    "Cross river gorilla",
    "Crow",
    "Crowned crane",
    "Crows",
    "Crucian carp",
    "Cuban boa",
    "Cuban cockroach",
    "Cuban solenodon",
    "Cuckoo",
    "Cuckoo bird",
    "Curlew",
    "Curly coated retriever",
    "Cuscus",
    "Cuttlefish",
    "Cuviers dwarf caimans",
    "Czechoslovakian wolfdog",
    "Dabra goby",
    "Dace",
    "Dachsador",
    "Dachshund",
    "Dalmadoodle",
    "Dalmador",
    "Dalmatian",
    "Damselfish",
    "Danio",
    "Danios",
    "Dapple dachshund",
    "Dark-eyed junco",
    "Darkling beetle",
    "Darter",
    "Darwin's fox",
    "Darwin's frog",
    "Darwin’s frog",
    "Dassie rat",
    "De brazza's monkeys",
    "Death adder",
    "Death's head cockroach",
    "Deathwatch beetle",
    "Deer",
    "Deer head chihuahua",
    "Deer mouse",
    "Deer tick",
    "Deerdegu-2",
    "Degu",
    "Degudik-dik-2",
    "Desert kingsnake",
    "Desert locust",
    "Desert rain frog",
    "Desert tortoise",
    "Deutsche bracke",
    "Devils coach horse beetle",
    "Devon rex",
    "Dhole",
    "Diamondback rattlesnake",
    "Dik dik",
    "Dik dikdogs",
    "Dik-dik",
    "Dilophosaurus",
    "Dimetrodon",
    "Dingo",
    "Dipper",
    "Dire wolf",
    "Discus",
    "Doberman pinscher",
    "Dodo",
    "Dog",
    "Dog salmon",
    "Dog tick",
    "Dogfish",
    "Dogo argentino",
    "Dogue de bordeaux",
    "Dolium shell",
    "Dolphin",
    "Dolphins",
    "Domestic ass",
    "Domestic fowl",
    "Domestic pigdragonfly",
    "Donkey",
    "Dorgi",
    "Dorkie",
    "Dormouse",
    "Dory",
    "Dotterel",
    "Double doodle",
    "Douc",
    "Dove",
    "Doxiepoo",
    "Doxle",
    "Draco volans lizard",
    "Dragon fly & damsel fly",
    "Dragonfish",
    "Dragonfly",
    "Dragonflydromedary camels",
    "Drever",
    "Drill",
    "Dromedary camel",
    "Dromedary camels",
    "Drongo",
    "Drum fish",
    "Drywood termite",
    "Drywood termites",
    "Dubia cockroach",
    "Duck",
    "Duck-billed platypus",
    "Ducks",
    "Dugong",
    "Dumeril's boa",
    "Dung beetle",
    "Dunker",
    "Dunlin",
    "Dunnock",
    "Dusky dolphin",
    "Dwarf boa",
    "Dwarf crocodile",
    "Dwarf hamster",
    "Eagle",
    "Eagle owl",
    "Eartheater",
    "Earthworm",
    "Earthworms",
    "Earwig",
    "Eastern barred bandicoot",
    "Eastern bluebird",
    "Eastern brown snake",
    "Eastern chipmunk",
    "Eastern chipmunks",
    "Eastern coral snake",
    "Eastern diamondback rattlesnake",
    "Eastern fence lizard",
    "Eastern glass lizard",
    "Eastern gorilla",
    "Eastern gray squirrel",
    "Eastern green mamba",
    "Eastern indigo snake",
    "Eastern lowland gorilla",
    "Eastern lowland gorillas",
    "Eastern phoebe",
    "Eastern racer",
    "Eastern rat snake",
    "Eastern wolf1200px-short-beaked_echidna_in_anbg",
    "Eastern woodrat",
    "Echidna",
    "Eclectus parrot",
    "Edible frog",
    "Eel",
    "Eelpout",
    "Eels",
    "Eft",
    "Egret",
    "Egyptian cobra",
    "Egyptian goose",
    "Egyptian mau",
    "Eider",
    "Eland",
    "Elasmosaurus",
    "Electric catfish",
    "Electric eel",
    "Elegant tern",
    "Elepaio",
    "Elephant",
    "Elephant seal",
    "Elephant shrew",
    "Elephant shrews",
    "Elephants",
    "Elk",
    "Emerald tree monitor",
    "Emperor penguin",
    "Emperor tamarin",
    "Emu",
    "Emu (jeuvenile)",
    "Emuerect-crested penguin",
    "English bulldog",
    "English cocker spaniel",
    "English cream golden retriever",
    "English foxhound",
    "English pointer",
    "English setter",
    "English shepherd",
    "English springer spaniel",
    "Entellus or hanuman monkey",
    "Entlebucher mountain dog",
    "Epagneul pont audemer",
    "Equatorial spitting cobra",
    "Erect-crested penguin",
    "Ermine",
    "Ermines",
    "Escolar",
    "Eskimo dog",
    "Eskipoo",
    "Estrela mountain dog",
    "Ethiopian wolf",
    "Eulachon",
    "Eurasian beaver",
    "Eurasian eagle owl",
    "Eurasian jay",
    "Eurasian lynx",
    "Eurasian nuthatch",
    "Eurasian water shrew",
    "Eurasian wolf",
    "Eurasian wryneck",
    "Euro",
    "European bear",
    "European bee-eater",
    "European common toad",
    "European corn borer",
    "European hare",
    "European ibex",
    "European otter",
    "European polecat",
    "European red squirrel",
    "European robin",
    "European tree frogs",
    "European wildcat",
    "Evening bat",
    "Eyelash viper",
    "Fainting goat",
    "Falcon",
    "Fallow deer",
    "False black widow spider",
    "False cobra",
    "False coral snake",
    "False killer whale",
    "False water cobra",
    "False widow spider",
    "Fangtooth",
    "Fat frog",
    "Feist",
    "Female garden spiders",
    "Fennec",
    "Fennec fox",
    "Fer-de-lance snake",
    "Ferret",
    "Ferruginous hawk",
    "Fiddler crab",
    "Field spaniel",
    "Field voleblue devil damsel",
    "Fierce snake",
    "Fiji blue devil damsel fish",
    "Fila brasileiro",
    "Fin whale",
    "Finch",
    "Finnish spitz",
    "Fiordland crested penguin",
    "Fire ant",
    "Fire eel",
    "Fire salamander",
    "Fire-bellied toad",
    "Firefly",
    "Fish",
    "Fisher",
    "Fisher cat",
    "Fishing cat",
    "Flamingo",
    "Flat coat retriever",
    "Flat headed cats",
    "Flat-coated retriever",
    "Flat-headed cat",
    "Flat-headed snake",
    "Flatworms",
    "Flea",
    "Flies",
    "Florida gar",
    "Florida panther",
    "Florida pompano",
    "Florida woods cockroach",
    "Flounder",
    "Flowerhorn fish",
    "Flowerpecker",
    "Fluke fish",
    "Fluke fish (summer flounder)",
    "Fly",
    "Flycatcher",
    "Flying dragon",
    "Flying fish",
    "Flying fox",
    "Flying fox bat",
    "Flying lemur",
    "Flying snake",
    "Flying squirrel",
    "Football fish",
    "Forest cobra",
    "Formosan mountain dog",
    "Fossa",
    "Fox",
    "Fox snakes",
    "Fox squirrel",
    "Fox terrier",
    "Foxhound",
    "French bulldog",
    "Frenchton",
    "Frengle",
    "Freshwater crocodile",
    "Freshwater eel",
    "Freshwater jellyfish",
    "Friesian",
    "Frigate bird",
    "Frigatebird",
    "Frilled coquette hummingbird",
    "Frilled lizard",
    "Frilled shark",
    "Frog",
    "Frogfish",
    "Frogmouth",
    "Fruit bat",
    "Fruit fly",
    "Fulmar",
    "Fungus beetle",
    "Funnel web spider",
    "Fur seal",
    "Gaboon viper",
    "Gadwall",
    "Galago lemur",
    "Galapagos barn owls",
    "Galapagos black tipped shark",
    "Galapagos brown noddy tern",
    "Galapagos brown pelican birds",
    "Galapagos brydes whale",
    "Galapagos dark billed cuckoo",
    "Galapagos dove",
    "Galapagos eels",
    "Galapagos fin whales",
    "Galapagos finches",
    "Galapagos flamingo",
    "Galapagos flightless cormorant sea bird",
    "Galapagos flycatcher bird",
    "Galapagos flycatcher birdgalapagos fur seal",
    "Galapagos fur seals",
    "Galapagos gecko",
    "Galapagos giant tortoise",
    "Galapagos great blue heron bird",
    "Galapagos great frigate bird",
    "Galapagos green sea turtle",
    "Galapagos hammerhead shark",
    "Galapagos hawkhoary bat",
    "Galapagos hoary bat",
    "Galapagos humpback whalegalapagos killer whale",
    "Galapagos killer whale – the orca",
    "Galapagos land iguana",
    "Galapagos lava gull bird",
    "Galapagos lava heron bird",
    "Galapagos lava lizard",
    "Galapagos marine iguana",
    "Galapagos masked booby bird",
    "Galapagos minke whale",
    "Galapagos mockingbird",
    "Galapagos nazca booby bird",
    "Galapagos penguin",
    "Galapagos rail bird",
    "Galapagos rays",
    "Galapagos red bat",
    "Galapagos red billed tropic bird",
    "Galapagos red footed booby bird",
    "Galapagos rice rat",
    "Galapagos sea lions",
    "Galapagos short eared owl",
    "Galapagos short finned pilot whale",
    "Galapagos silky shark",
    "Galapagos smooth billed ani bird",
    "Galapagos snakes",
    "Galapagos sperm whalestorm petrel bird",
    "Galapagos storm petrel bird",
    "Galapagos swallow tailed gull",
    "Galapagos tortoise",
    "Galapagos waved albatross",
    "Galapagos whale shark",
    "Galapagos whimbrel birds",
    "Galapagos white cheeked pintail duckwhite tipped reef shark",
    "Galapagos white tipped reef shark",
    "Galapagos willet bird",
    "Galapagos yellow warbler bird",
    "Galapagos yellow-crowned night heron",
    "Gannet",
    "Gar",
    "Garden eel",
    "Garden spider",
    "Garter snake",
    "Gaur",
    "Gavial",
    "Gazelle",
    "Gecko",
    "Gemsbok",
    "Genet",
    "Gentoo penguin",
    "Geoffroys tamarin",
    "Geoffroy’s tamarin",
    "Geometric tent tortoise",
    "Gerberian shepsky",
    "Gerbil",
    "Gerenuk",
    "German cockroach",
    "German pinscher",
    "German shepard",
    "German shepherd",
    "German shepherd guide",
    "German sheppit",
    "German sheprador",
    "German shorthaired pointer",
    "German spitz",
    "Gharial",
    "Gharialgiant anteater",
    "Ghost bat",
    "Ghost catfish",
    "Ghost crab",
    "Giant african land snail",
    "Giant anteater",
    "Giant armadillo",
    "Giant clam",
    "Giant ground sloth",
    "Giant grouper fish",
    "Giant groupera giant pacific octopus",
    "Giant pacific octopus",
    "Giant panda",
    "Giant panda bear",
    "Giant sable antelope",
    "Giant salamander",
    "Giant schnauzer",
    "Giant schnoodle",
    "Giant squid",
    "Gibbon",
    "Gila monster",
    "Giraffe",
    "Glass frog",
    "Glass lizard",
    "Glechon",
    "Glen of imaal terrier",
    "Glow worm",
    "Gnat",
    "Gnu",
    "Goat",
    "Goats",
    "Goberian",
    "Goblin shark",
    "Goby",
    "Gold, silver and blue monkeys",
    "Goldador",
    "Golden cat",
    "Golden dox",
    "Golden eagle",
    "Golden lancehead",
    "Golden lion tamarin",
    "Golden masked owl",
    "Golden newfie",
    "Golden oriole",
    "Golden pheasant",
    "Golden pyrenees",
    "Golden retriever",
    "Golden saint",
    "Golden shepherd",
    "Golden-crowned flying fox",
    "Goldendoodle",
    "Goldeneye",
    "Goldfinch",
    "Goldfish",
    "Goliath birdeater",
    "Goliath frog",
    "Goliath tigerfish",
    "Gomphotherium",
    "Goonch catfish",
    "Goose",
    "Gopher",
    "Gopher snake",
    "Gopher tortoise",
    "Gordon setter",
    "Gorilla",
    "Gorillas",
    "Goshawk",
    "Gouldian finch",
    "Gourami",
    "Grackle",
    "Grass carp",
    "Grass snake",
    "Grasshopper",
    "Grasshopper mouse",
    "Gray fox",
    "Gray owl",
    "Gray tree frog",
    "Grayling",
    "Great barracuda",
    "Great bittern",
    "Great black cockatoo",
    "Great blue heron",
    "Great crested flycatcher",
    "Great crested newt",
    "Great dane",
    "Great danoodle",
    "Great egret",
    "Great green macaw",
    "Great plains rat snake",
    "Great plover",
    "Great pyrenees",
    "Great white african pelican birds",
    "Great white shark",
    "Greater flamingo",
    "Greater honeyguide",
    "Greater horseshoe bat",
    "Greater mouse-eared bat",
    "Greater spot-nosed monkeysgreen caterpillars",
    "Greater swiss mountain dog",
    "Green anaconda",
    "Green anole",
    "Green bee-eater",
    "Green caterpillarsa green cheeked conure",
    "Green cheeked conure",
    "Green crabs",
    "Green frog",
    "Green heron",
    "Green jack",
    "Green jay",
    "Green mamba",
    "Green rat snake",
    "Green scarab beetle",
    "Green snake",
    "Green tree frog",
    "Green tree python",
    "Green turtle",
    "Greenland dog",
    "Greenland shark",
    "Grevy's zebra",
    "Grey heron",
    "Grey jungle fowl bird",
    "Grey loerie birdgrey partridge",
    "Grey mouse lemur",
    "Grey partridge",
    "Grey reef shark",
    "Grey seal",
    "Grey wolf",
    "Greyhound",
    "Griffon vulture",
    "Griffonshire",
    "Grivet monkeys",
    "Grizzly bear",
    "Groenendael",
    "Ground beetle",
    "Ground centipede",
    "Ground snake",
    "Ground squirrel",
    "Groundhog",
    "Groundhog (woodchuck)",
    "Groundhogs",
    "Grouper",
    "Grouse",
    "Guan",
    "Guanaco",
    "Guinea fowl",
    "Guinea pig",
    "Guinea pigs",
    "Guppy",
    "Gyr falcon",
    "Habu snake",
    "Haddock",
    "Hagfish",
    "Hake",
    "Halibut",
    "Hamerkop bird",
    "Hammerhead shark",
    "Hamster",
    "Hamsters",
    "Harbor porpoise",
    "Harbor seal",
    "Harbour porpoise",
    "Hardhead catfish",
    "Hare",
    "Harlequin duck",
    "Harlequin snake",
    "Harp seal",
    "Harpy eagle",
    "Harrier",
    "Harrier hawk",
    "Harris hawk",
    "Hartebeest",
    "Harvest mice",
    "Havanese",
    "Havapoo",
    "Havashire",
    "Hawaiian crow",
    "Hawaiian goose",
    "Hawaiian monk seal",
    "Hawk",
    "Hawk moth caterpillar",
    "Hawksbill turtle",
    "Hazel dormouse",
    "Hectors dolphinhedgehogs",
    "Hedgehog",
    "Hedgehong",
    "Hellbender",
    "Hercules beetle",
    "Hercules moth",
    "Hermit crab",
    "Hermit crabs",
    "Heron",
    "Herring",
    "Herring gull",
    "Highland cattle",
    "Himalayan",
    "Hippopotamus",
    "Hissing cockroach",
    "Hoary bat",
    "Hoatzin",
    "Hobo spider",
    "Hobo spiderhoney bees",
    "Hognose snake",
    "Hokkaido",
    "Honduran white bat",
    "Honey badger",
    "Honey bee",
    "Honey bee characteristics",
    "Honey beehoney bees",
    "Honey buzzard",
    "Hooded oriole",
    "Hooded seal",
    "Hook-nosed sea snake",
    "Hoopoe",
    "Hoopoe birds",
    "Horgi",
    "Horn shark",
    "Hornbill",
    "Horned adder",
    "Horned frog",
    "Horned lizard",
    "Horned puffin",
    "Horned viper",
    "Hornet",
    "Hornets",
    "Horny toad",
    "Horse",
    "Horse shoe crab",
    "Horsefly",
    "Horses",
    "Horseshoe bat",
    "Horseshoe crab",
    "Horseshoe crabs",
    "Hound",
    "House centipede",
    "House finch",
    "House martin",
    "House mouse",
    "House sparrow",
    "House wren",
    "Housefly",
    "Hoverfly",
    "Howler monkey",
    "Howler monkeys",
    "Human",
    "Humboldt penguin",
    "Humboldt squid",
    "Hummingbird",
    "Hummingbird hawk-moth",
    "Hummingbird moths",
    "Humpback whale",
    "Humphead wrasse",
    "Huntaway",
    "Huntsman spider",
    "Huskador",
    "Huskita",
    "Husky",
    "Husky jack",
    "Huskydoodle",
    "Hydrozoan jellyfish",
    "Hyena",
    "Hyrax",
    "Iberian frog",
    "Ibex",
    "Ibis",
    "Ibisbill bird",
    "Ibizan hound",
    "Icefish",
    "Iceland gull",
    "Icelandic sheepdog",
    "Icterine warbler",
    "Idaho ground squirrel",
    "Idaho pocket gopher",
    "Iguana",
    "Immortal jellyfish",
    "Impala",
    "Imperial eagle",
    "Imperial moth",
    "Inchworm",
    "Indian bullfrog",
    "Indian bush rat",
    "Indian cobra",
    "Indian cuckoo bird",
    "Indian elephant",
    "Indian flying fox",
    "Indian gazelle",
    "Indian gerbil",
    "Indian giant squirrel",
    "Indian hare",
    "Indian palm squirrel",
    "Indian rhinoceros",
    "Indian ringnecked parakeet",
    "Indian skimmer bird",
    "Indian star tortoise",
    "Indigo snake",
    "Indochinese tiger",
    "Indri",
    "Inland taipan",
    "Insect",
    "Insects",
    "Insular mole",
    "Inyo shrew",
    "Iriomote cat",
    "Irish doodle",
    "Irish elk",
    "Irish setter",
    "Irish terrier",
    "Irish water spaniel",
    "Irish wolf",
    "Irish wolfhound",
    "Irukandji jellyfish",
    "Island fox",
    "Island gray fox",
    "Island mouse",
    "Isopod",
    "Italian greyhound",
    "Italian wall lizard",
    "Italian wolf",
    "Ivory gull",
    "Ivory-billed woodpecker",
    "Jabiru",
    "Jacamar",
    "Jacana",
    "Jack dempsey",
    "Jack fish",
    "Jack rabbit",
    "Jack russel",
    "Jack russell",
    "Jackabee",
    "Jackal",
    "Jackdaw",
    "Jackrabbit",
    "Jackson's chameleon",
    "Jaeger",
    "Jaguar",
    "Jaguarundi",
    "Jaguarundi cat",
    "Jamaican boa",
    "Jambu fruit dovejapanese spider crabs",
    "Japanese beetle",
    "Japanese chin",
    "Japanese hare",
    "Japanese macaque",
    "Japanese mole",
    "Japanese rat snake",
    "Japanese spider crabs",
    "Japanese spitz",
    "Japanese squirrel",
    "Japanese terrier",
    "Javan langur",
    "Javan pig",
    "Javan pipistrelle",
    "Javan rhinoceros",
    "Javan slit-faced bat",
    "Javan tiger",
    "Javan tree shrew",
    "Javanese",
    "Jay",
    "Jelly fish",
    "Jellyfish",
    "Jerboa",
    "Jico deer mouse",
    "John dory",
    "Jonah crab",
    "Joro spider",
    "Jumping spider",
    "Junco",
    "Jungle cat",
    "Jungle palm squirrel",
    "Jungle shrew",
    "Junglefowl",
    "Junin grass mouse",
    "Junin red squirrel",
    "Juniper vole",
    "Kagu",
    "Kai ken",
    "Kaka",
    "Kakapo",
    "Kangal",
    "Kangaroo",
    "Kangaroo rat",
    "Katipo spider",
    "Katydid",
    "Kea",
    "Kea parrotkestrel",
    "Keel billed toucan",
    "Keel-billed toucan",
    "Keelback",
    "Keeshond",
    "Kenyan sand boa",
    "Kerry blue terrier",
    "Kestrel",
    "Kestrel bird",
    "Keta salmon",
    "Key deer",
    "Kiko goat",
    "Killdeer",
    "Killer bee",
    "Killer whale",
    "Killer whale (orca)",
    "Kinabalu giant red leech",
    "Kinder goat",
    "King cobra",
    "King cobra snakes",
    "King crab",
    "King eider",
    "King penguin",
    "King penguinking salmon",
    "King rat snake",
    "King salmon",
    "King shepherd",
    "King snake",
    "King vulture",
    "Kingfisher",
    "Kinkajou",
    "Kirk’s dik-dik",
    "Kirtland's snake",
    "Kishu",
    "Kit fox",
    "Kite",
    "Kitten",
    "Kittens",
    "Kivu shrew",
    "Kiwi",
    "Klipspringer",
    "Knifefish",
    "Koala",
    "Kob",
    "Kodiak bear",
    "Kodkod",
    "Koi",
    "Koi fish",
    "Komodo dragon",
    "Komodo dragonkrill",
    "Kooikerhondje",
    "Kookaburra",
    "Koolie",
    "Korean field mouse",
    "Korean hare",
    "Kori bustard",
    "Korinch’s rat",
    "Kouprey",
    "Kowari",
    "Krait",
    "Krill",
    "Kudu",
    "Kulan",
    "Kune kune",
    "Kuvasz",
    "La",
    "Labahoula",
    "Labmaraner",
    "Labradane",
    "Labradoodle",
    "Labrador retriever",
    "Labraheeler",
    "Lacewing",
    "Ladybird",
    "Ladybird (bre) – ladybug (name)",
    "Ladybug",
    "Lagotis",
    "Lake sturgeon",
    "Lake trout",
    "Lake whitefish",
    "Lakeland terrier",
    "Lamb",
    "Lammergeier",
    "Lamprey",
    "Lancashire heeler",
    "Land crab",
    "Lappet-faced vulture",
    "Lapponian herder",
    "Lapwing",
    "Laughing kookaburra",
    "Lawnmower blenny",
    "Lazarus lizard",
    "Leaf-tailed gecko",
    "Leafcutter ant",
    "Leatherback sea turtle",
    "Leech",
    "Lemming",
    "Lemmings",
    "Lemon shark",
    "Lemur",
    "Leonberger",
    "Leopard",
    "Leopard cat",
    "Leopard frog",
    "Leopard gecko",
    "Leopard lizard",
    "Leopard seal",
    "Leopard shark",
    "Leopard tortoise",
    "Leopard tortoiselion",
    "Lhasa apso",
    "Lhasapoo",
    "Liger",
    "Lion",
    "Lion's mane jellyfish",
    "Lioness",
    "Lionfish",
    "Lions",
    "Little brown bat",
    "Little fairy penguin",
    "Little penguin",
    "Livyatan",
    "Lizard",
    "Lizardfish",
    "Lizards",
    "Llama",
    "Llama & camel",
    "Loach",
    "Lobster",
    "Locust",
    "Loggerhead turtle",
    "Lone star tick",
    "Long eared owl",
    "Long horned beetle",
    "Long-eared owl",
    "Long-haired rottweiler",
    "Long-tailed tit",
    "Longhorn cowfish",
    "Longnose gar",
    "Longspur",
    "Loon",
    "Lorikeet",
    "Loris",
    "Lory",
    "Louse",
    "Lovebird",
    "Lowchen",
    "Lumpfish",
    "Lungfish",
    "Lynx",
    "Lyrebird",
    "Macaque",
    "Macaque monkeys",
    "Macaroni penguin",
    "Macaw",
    "Mackenzie wolf",
    "Mackerel",
    "Madagascar hissing cockroach",
    "Madagascar tree boa",
    "Magellanic penguin",
    "Maggot",
    "Magpie",
    "Magpiemanatee",
    "Mahi mahi (dolphin fish)",
    "Maiasaura",
    "Maine coon",
    "Mako shark",
    "Malayan civet",
    "Malayan krait",
    "Malayan tiger",
    "Mallard",
    "Mallard duck",
    "Malteagle",
    "Maltese",
    "Maltese shih tzu",
    "Maltipoo",
    "Mamba",
    "Mammoth",
    "Mamushi snake",
    "Man of war jellyfish",
    "Man-o\'-war",
    "Manatee",
    "Manateemaned wolf",
    "Mancha goat",
    "Manchester terrier",
    "Mandarin duck",
    "Mandarin rat snake",
    "Mandrill",
    "Maned wolf",
    "Maned wolfthe",
    "Mangrove snake",
    "Manta ray",
    "Mantella frog",
    "Mantis shrimp",
    "Manx shearwater bird",
    "Map turtle",
    "Mara",
    "Marabou stork",
    "Marble fox",
    "Marine angelfish",
    "Marine iguana",
    "Marine invertebrate",
    "Marine toad",
    "Markhor",
    "Marlin",
    "Marmoset",
    "Marmot",
    "Marsh frog",
    "Marten",
    "Masai giraffe",
    "Masked angelfish",
    "Masked finfoot bird",
    "Masked palm civet",
    "Massasauga",
    "Mastadon",
    "Mastador",
    "Mastiff",
    "Mayfly",
    "Meadowlark",
    "Meagle",
    "Mealy parrot",
    "Mealybug",
    "Meerkat",
    "Megalodon",
    "Megamouth shark",
    "Mekong giant catfish",
    "Merganser",
    "Merino sheep",
    "Merlin",
    "Mexican alligator lizard",
    "Mexican black kingsnake",
    "Mexican eagle (northern crested caracara)",
    "Mexican free-tailed bat",
    "Mexican mole lizard",
    "Mexican wolfbritish mice types",
    "Mice",
    "Midget faded rattlesnake",
    "Miki",
    "Military macaw parrot",
    "Milk fish",
    "Milk snake",
    "Milkfish",
    "Milkweed beetle",
    "Millipede",
    "Millipedes",
    "Mini labradoodle",
    "Miniature bull terrier",
    "Miniature husky",
    "Miniature pinscher",
    "Mink",
    "Minke whale",
    "Minnow",
    "Minnows",
    "Mississippi kite",
    "Mite",
    "Moa",
    "Moccasin",
    "Moccasin snake",
    "Mockingbird",
    "Mojarra",
    "Mojave rattlesnake",
    "Mola mola (ocean sunfish)",
    "Mole",
    "Mole cricket",
    "Mole rat",
    "Mole snake",
    "Mollusk",
    "Molly",
    "Moloch",
    "Monarch butterfly",
    "Mongoose",
    "Mongrel",
    "Monitor lizard",
    "Monkey",
    "Monkeys",
    "Monkfish",
    "Monocled cobra",
    "Monte iberia eleuth",
    "Moon bear",
    "Moon fish",
    "Moon jellyfish",
    "Moorhen",
    "Moose",
    "Moray eel",
    "Morkie",
    "Morpho butterfly",
    "Moscow watchdog",
    "Mosquito",
    "Moth",
    "Mountain beaver",
    "Mountain bluebird",
    "Mountain cur",
    "Mountain feist",
    "Mountain goat",
    "Mountain gorilla",
    "Mountain gorillasmountain zebra",
    "Mountain lion",
    "Mountain sheep",
    "Mountain zebra",
    "Mourning dove",
    "Mouse",
    "Mouse spider",
    "Moving leaf insect",
    "Mozambique spitting cobra",
    "Mud dauber waspmusk ox",
    "Mud snake",
    "Mudi",
    "Mudpuppy",
    "Mule",
    "Mule deer",
    "Mulga snake",
    "Muntjac",
    "Muscovy duck",
    "Musk ox",
    "Muskox",
    "Muskrat",
    "Mussurana snake",
    "Mustang",
    "Muttaburrasaurus",
    "Myna bird",
    "Nabarlek",
    "Naked mole rat",
    "Nalolo",
    "Nandu",
    "Napu",
    "Narwhal",
    "Nase",
    "Natterjack",
    "Natterjack toad",
    "Nautilus",
    "Neanderthal",
    "Neapolitan mastiff",
    "Nebelung",
    "Neddicky",
    "Needlefish",
    "Nematode",
    "Nene",
    "Neon tetra",
    "Neptune grouper",
    "New world monkeys",
    "New world tarantula spider",
    "Newfoundland",
    "Newfypoo",
    "Newt",
    "Nicator",
    "Nicobar pigeon",
    "Nigerian goat",
    "Night adder",
    "Night heron",
    "Night monkey",
    "Night snake",
    "Nightcrawler",
    "Nightfish",
    "Nighthawk",
    "Nightingale",
    "Nightjar",
    "Nile crocodile",
    "Nilgai",
    "Ningaui",
    "Nkupe",
    "No see ums",
    "Noctule",
    "Noddy",
    "Noodlefish",
    "Norfolk terrier",
    "North african ground hornbill",
    "North african wild ass",
    "North american black bear",
    "Northern alligator lizard",
    "Northern cardinal",
    "Northern fur seal",
    "Northern inuit dog",
    "Northern pike",
    "Northern short-tailed shrew",
    "Northern water snake",
    "Norwegian buhund",
    "Norwegian elkhound",
    "Norwegian forest",
    "Norwegian lundehund",
    "Norwich terrier",
    "Nose-horned viper",
    "Nova scotia duck tolling retriever",
    "Nubian goat",
    "Nudibranch",
    "Numbat",
    "Numbray",
    "Nunbird",
    "Nunlet",
    "Nurse shark",
    "Nurseryfish",
    "Nuthatch",
    "Nutria",
    "Nutria rat",
    "Nyala",
    "Nënë",
    "Oak toad",
    "Oarfish",
    "Ocellaris clownfish",
    "Ocelot",
    "Octopus",
    "Oil fish",
    "Oilbird",
    "Okapi",
    "Old english sheepdog",
    "Old world monkeys",
    "Old world tarantula spiders",
    "Olive baboon",
    "Olive ridley sea turtle",
    "Olive sea snake",
    "Olm",
    "Opossum",
    "Opossums",
    "Orang-utan",
    "Orange-crowned warbler",
    "Orangutan",
    "Orb weaver",
    "Orb weaver spiders",
    "Orca",
    "Oriole",
    "Ornate chorus frog",
    "Ornate hawk-eagle",
    "Ornithomimus",
    "Ortolan bunting",
    "Oryx",
    "Oryx (antelope)",
    "Oscar fish",
    "Osprey",
    "Ospreyostrich",
    "Ostrich",
    "Ostrich birds",
    "Otter",
    "Otterhound",
    "Oviraptor",
    "Owl",
    "Owl butterfly",
    "Owls",
    "Ox",
    "Oyster",
    "Oyster catcher",
    "Oyster toadfish",
    "Oystercatcher",
    "Paca",
    "Pack rat",
    "Pacman frog",
    "Paddlefish",
    "Pademelon",
    "Paint horse",
    "Painted turtle",
    "Palm civet",
    "Pampas cat",
    "Panda",
    "Panda bear",
    "Pangolin",
    "Panther",
    "Panther chameleon",
    "Pantropical spotted dolphins",
    "Paper waspparasitic bees",
    "Papillon",
    "Paradise flying snake",
    "Parakeet",
    "Parasaurolophus",
    "Parasitic bees",
    "Parrot",
    "Parrot snake",
    "Parrotfish",
    "Parrotlet",
    "Parson russell terrier",
    "Partridge",
    "Passenger pigeon",
    "Patagotitan",
    "Patas monkey",
    "Patterdale terrier",
    "Peacock",
    "Peacock butterfly",
    "Peacock spider",
    "Peafowl",
    "Peafowl peacock",
    "Peagle",
    "Peccary (javelina)",
    "Peekapoo",
    "Pekingese",
    "Pelican",
    "Pembroke welsh corgi",
    "Penguin",
    "Pennant-winged night jar",
    "Pennsylvania wood cockroach",
    "Peppermint angelfish",
    "Percheron",
    "Pere davids deer",
    "Pere david’s deer",
    "Peregrine falcon",
    "Peringuey's adder",
    "Permit",
    "Perro de presa canario",
    "Persian",
    "Peruvian foxpigs",
    "Peruvian inca orchid",
    "Pesquet's parrot (dracula parrot)",
    "Petit basset griffon vendéen",
    "Petite goldendoodle",
    "Petrel",
    "Pheasant",
    "Philippine cobra",
    "Phorusrhacos",
    "Pied ball python",
    "Pied tamarin",
    "Pig",
    "Pig deer",
    "Pig-footed bandicoot",
    "Pigeon",
    "Pigs",
    "Pika",
    "Pika & hyrax",
    "Pike",
    "Pike fish",
    "Pileated woodpecker",
    "Pine marten",
    "Pine snake",
    "Pink fairy armadillo",
    "Pink salmon",
    "Pinscher dog",
    "Pintail",
    "Pipe snake",
    "Pipefish",
    "Piranha",
    "Piranha fishplains zebra",
    "Pit bull",
    "Pit viper",
    "Pitador",
    "Pitsky",
    "Pitta",
    "Plains hognose snake",
    "Plains zebra",
    "Platinum arowana",
    "Platy",
    "Platypus",
    "Pleco",
    "Plover",
    "Pocket beagle",
    "Pocket pitbull",
    "Pointer",
    "Poison arrow frogs",
    "Poison arrow frogspoisonous caterpillars",
    "Poison dart frog",
    "Poisonous caterpillars",
    "Polar bear",
    "Polecat",
    "Polecatpollan fish",
    "Polish lowland sheepdog",
    "Polka dot stingray",
    "Pollan fish",
    "Pollock",
    "Polyphemus moth",
    "Pomapoo",
    "Pomchi",
    "Pomeagle",
    "Pomeranian",
    "Pomfret",
    "Pompano",
    "Pomsky",
    "Pond skater",
    "Poochon",
    "Poodle",
    "Poodles",
    "Poogle",
    "Pool frog",
    "Porbeagle shark",
    "Porcelain crab",
    "Porcupine",
    "Porcupines",
    "Porpoise",
    "Possum",
    "Pot belly pig",
    "Potoo",
    "Potoroo",
    "Potter wasps",
    "Potto",
    "Prairie chicken",
    "Prairie dog",
    "Prairie rattlesnake",
    "Prawn",
    "Praying mantis",
    "Preuss's monkey",
    "Proboscis monkey",
    "Procoptodon",
    "Pronghorn",
    "Psittacosaurus",
    "Ptarmigan",
    "Pudelpointer",
    "Puff adder",
    "Puffer fish",
    "Pufferfish",
    "Puffin",
    "Puffins",
    "Pug",
    "Pugapoo",
    "Puggle",
    "Pugshire",
    "Puma",
    "Pumi",
    "Puppy",
    "Purple emperor",
    "Purple emperor butterfly",
    "Purple finch",
    "Purple martin",
    "Puss moth",
    "Pygmy goat",
    "Pygmy hippopotamus",
    "Pygmy marmoset",
    "Pygmy marmoset (finger monkey)",
    "Pygora goat",
    "Pyrador",
    "Pyredoodle",
    "Pyrops candelaria (lantern flies)",
    "Python",
    "Qinling panda",
    "Quagga",
    "Quagga zebra",
    "Quagga zebraquokka-3",
    "Quahog",
    "Quail",
    "Quaira spiny rat",
    "Quarter horse",
    "Quechuan hocicudo",
    "Queen alexandra’s birdwing",
    "Queen angelfish",
    "Queen of sheba’s gazelle",
    "Queen snake",
    "Queen snapper",
    "Queen triggerfish",
    "Queensland grouper",
    "Queensland tube-nosed bat",
    "Quelea (red-billed)",
    "Quetzal",
    "Quokka",
    "Quoll",
    "Quolls",
    "Quollsrabbits",
    "Rabbit",
    "Rabbit & frog",
    "Rabbitsraccoon",
    "Raccoon",
    "Raccoon dog",
    "Racer snake",
    "Racoon",
    "Racoon dog",
    "Racoons",
    "Radiated tortoise",
    "Ragamuffin",
    "Ragdoll",
    "Raggle",
    "Rail",
    "Rainbow bee eater",
    "Rainbow bee eaterratel",
    "Rainbow boa",
    "Rainbow shark",
    "Rainbow snake",
    "Rainbow trout",
    "Rat",
    "Rat snake",
    "Rat snakes",
    "Rat squirrel",
    "Rat terrier",
    "Ratel",
    "Rattlesnake",
    "Rattlesnakes",
    "Raven",
    "Red angus",
    "Red back jumping spiders",
    "Red bat",
    "Red british squirrel",
    "Red deer",
    "Red diamondback rattlesnake",
    "Red finch",
    "Red firefish",
    "Red fox",
    "Red kangaroo",
    "Red kite",
    "Red kitered panda",
    "Red knee tarantula",
    "Red mullet fis",
    "Red panda",
    "Red racer snake",
    "Red rock crabs",
    "Red slender loris",
    "Red spitting cobra",
    "Red squirrel",
    "Red tail boa (common boa)",
    "Red tailed hawk",
    "Red winged blackbird",
    "Red wolf",
    "Red wood ants (female & male)",
    "Red-backed shrike",
    "Red-bellied black snake",
    "Red-billed quelea bird",
    "Red-eared slider",
    "Red-eyed tree frog",
    "Red-handed tamarin",
    "Red-headed vulture",
    "Red-lipped batfish",
    "Red-tailed hawk",
    "Red-winged blackbird",
    "Redback spider",
    "Redbone coonhound",
    "Redtail catfish",
    "Redwing",
    "Reef shark",
    "Reeves\'s pheasant",
    "Reindeer",
    "Remora",
    "Reticulated giraffe",
    "Reticulated python",
    "Rhea",
    "Rhino",
    "Rhino viper",
    "Rhinoceros",
    "Rhinoceros beetle",
    "Rhombic egg-eater snake",
    "Ribbon eel",
    "Ribbon snake",
    "Rigatella snail",
    "Right whales",
    "Ring-billed gull",
    "Ringed kingfisher",
    "Ringtail",
    "Rinkhals snake",
    "Risso's dolphin",
    "River dolphin",
    "River otter",
    "River turtle",
    "Roadrunner",
    "Robin",
    "Roborovski hamsters",
    "Rock crab",
    "Rock hyrax",
    "Rock python",
    "Rock thrush",
    "Rockfish",
    "Rockhopper penguin",
    "Rodents",
    "Roe deer",
    "Rooster",
    "Rosalie beetle",
    "Rose-breasted grosbeak",
    "Roseate spoonbill",
    "Rosy boa",
    "Rottsky",
    "Rottweiler",
    "Rough green snake",
    "Rough-toothed dolphins",
    "Royal penguin",
    "Rubber boa",
    "Ruby-throated hummingbird",
    "Rudd",
    "Ruddy duck",
    "Ruddy turnstone",
    "Ruff",
    "Russell terrier",
    "Russian bear dog",
    "Russian blue",
    "Russian tortoise",
    "Saanen goat",
    "Saarloos wolfdog",
    "Saber tooth tiger",
    "Saber-toothed tiger",
    "Sable",
    "Sable antelope",
    "Sable black german shepherd",
    "Sable ferret",
    "Sabre-toothed tiger",
    "Sacred ibis bird",
    "Sage grouse",
    "Saiga",
    "Saiga antelope",
    "Sailfish",
    "Saint berdoodle",
    "Saint bernard",
    "Saint shepherd",
    "Saki monkeys",
    "Salamander",
    "Sally lightfoot crabsand lizard",
    "Salmon",
    "Salmon shark",
    "Saltwater crocodile",
    "Saluki",
    "Sambar",
    "Samoyed",
    "San francisco garter snake",
    "Sand boa",
    "Sand cat",
    "Sand crab",
    "Sand dollar",
    "Sand lizard",
    "Sand star",
    "Sand tiger shark",
    "Sand viper",
    "Sanderling",
    "Sandhill crane",
    "Sandpiper",
    "Saola",
    "Sardines",
    "Satanic leaf-tailed gecko",
    "Sauropoda",
    "Savanna goat",
    "Savannah monitor",
    "Savannah sparrow",
    "Sawfish",
    "Scarab beetle",
    "Scarlet ibis",
    "Scarlet kingsnake",
    "Scarlet macaw",
    "Schipperke",
    "Schneagle",
    "Schneider's dwarf caiman",
    "Schnoodle",
    "Scimitar-horned oryx",
    "Scorpion",
    "Scorpion fish",
    "Scottish crossbill",
    "Scottish terrier",
    "Screamer",
    "Screech owl",
    "Scrotum frog",
    "Sculpin",
    "Sea anemone",
    "Sea dragon",
    "Sea eagle",
    "Sea horse",
    "Sea lion",
    "Sea otter",
    "Sea roach",
    "Sea slug",
    "Sea snake",
    "Sea snakes",
    "Sea sponge",
    "Sea squirt",
    "Sea turtle",
    "Sea urchin",
    "Sea urchinseagull",
    "Seagull",
    "Seahorse",
    "Seal",
    "Seals",
    "Sealyham terrier",
    "Secretary bird",
    "Sei whale",
    "Senegal parrot",
    "Serval",
    "Serval cat",
    "Servalshark",
    "Shad",
    "Shark",
    "Sharkdomestic sheep",
    "Sharp-tailed snake",
    "Shearwater",
    "Sheep",
    "Sheepadoodle",
    "Shells",
    "Shepadoodle",
    "Shepkita",
    "Shepweiler",
    "Shiba inu",
    "Shih poo",
    "Shih tzu",
    "Shoebill stork",
    "Shollie",
    "Short finned pilot whale",
    "Shoveler",
    "Shrew",
    "Shrike",
    "Shrimp",
    "Siamese",
    "Siamese fighting fish",
    "Siberian",
    "Siberian cat",
    "Siberian husky",
    "Siberian ibex",
    "Siberian retriever",
    "Siberian tiger",
    "Siberpoo",
    "Sidewinder",
    "Silk worm",
    "Silkie chicken",
    "Silkworm moths",
    "Silky terrier",
    "Silver dollar",
    "Silver labrador",
    "Silvery gibbon",
    "Sinosauropteryx",
    "Siren",
    "Six eyed sand spider",
    "Sixgill shark",
    "Skate",
    "Skate fish",
    "Skimmer",
    "Skink",
    "Skink lizard",
    "Skipjack",
    "Skipjack tuna",
    "Skipper butterflies",
    "Skunk",
    "Skye terrier",
    "Skylark",
    "Skylark bird",
    "Sleeper shark",
    "Slender loris",
    "Slender lorises",
    "Slipper lobster",
    "Sloth",
    "Sloth bear",
    "Slotha slow worm",
    "Sloths",
    "Slow loris",
    "Slow worm",
    "Slow wormslug",
    "Slug",
    "Smelt",
    "Smokybrown cockroach",
    "Smooth fox terrier",
    "Smooth green snake",
    "Smooth snake",
    "Smoothhound shark",
    "Snail",
    "Snake",
    "Snake-necked turtle",
    "Snakehead",
    "Snakes",
    "Snapping turtle",
    "Snares penguin",
    "Snipe",
    "Snipefish",
    "Snook fish",
    "Snorkie",
    "Snouted cobra",
    "Snow crab",
    "Snow goose",
    "Snow leopard",
    "Snowshoe",
    "Snowshoe hare",
    "Snowy owl",
    "Sockeye salmon",
    "Softshell turtle",
    "Sole",
    "Solitary bees",
    "Somali",
    "Song sparrow",
    "Song thrush",
    "Song thrush bird",
    "Sooty phalanger (brush-tailed possums",
    "Sora",
    "South china tiger",
    "Southern black racer",
    "Southern hognose snake",
    "Southern pacific rattlesnake",
    "Southern short-tailed shrew",
    "Southern short-tailed shrews",
    "Spadefoot toad",
    "Spanador",
    "Spanish goat",
    "Spanish mackerel",
    "Spanish mastiff",
    "Sparrow",
    "Sparrowhawk",
    "Speckled kingsnake",
    "Spectacled bear",
    "Spectacled caiman",
    "Spectacled/common caiman",
    "Sperm whale",
    "Spider",
    "Spider ball python",
    "Spider monkey",
    "Spider wasp",
    "Spider-tailed horned viper",
    "Spiders",
    "Spinner dolphin",
    "Spinner dolphins",
    "Spinner shark",
    "Spinone italiano",
    "Spinosaurus",
    "Spiny dogfish",
    "Spiny hill turtle",
    "Spiny lobster",
    "Spiny lobsterspotted beetle",
    "Spitting cobra",
    "Spixs macaw",
    "Spix’s macaw",
    "Splendar beetle",
    "Sponge",
    "Spoonbill",
    "Spotted beetle",
    "Spotted eagle",
    "Spotted gar",
    "Spotted lanternfly",
    "Spotted salamander",
    "Sprat",
    "Spring haas",
    "Springador",
    "Springbok",
    "Springerdoodle",
    "Squash beetle",
    "Squid",
    "Squirrel",
    "Squirrel monkey",
    "Squirrel monkeys",
    "Squirrelfish",
    "Sri lankan elephant",
    "St andrews cross spider",
    "Stabyhoun",
    "Staffordshire bull terrier",
    "Stag beetle",
    "Staghound",
    "Standard schnauzer",
    "Star-nosed mole",
    "Starfish",
    "Stargazer fish",
    "Starling",
    "Steelhead salmon",
    "Steer",
    "Stegosaurus",
    "Steller's sea cow",
    "Stellers sea cow",
    "Stellers sea cowstingless bees",
    "Stick insect",
    "Stickleback fish",
    "Stiletto snake",
    "Stingless bees",
    "Stingray",
    "Stink bugs",
    "Stoat",
    "Stone crab",
    "Stone curlew",
    "Stone dwelling centipede",
    "Stork",
    "Striped dolphins",
    "Striped hyena",
    "Striped rocket frog",
    "Sturgeon",
    "Sucker fish",
    "Sugar glider",
    "Sugar maple borer beetle",
    "Sulcata tortoise",
    "Sumatran elephant",
    "Sumatran orang-utan",
    "Sumatran orangutan",
    "Sumatran rhinoceros",
    "Sumatran tiger",
    "Sun bear",
    "Sunbeam snake",
    "Sunbird",
    "Sunfish",
    "Surgeonfish",
    "Surinam toad",
    "Swai fish",
    "Swallow",
    "Swan",
    "Swedish vallhund",
    "Swift",
    "Sword billed humming bird",
    "Swordfish",
    "Syrian hamster",
    "Taco terrier",
    "Tadpoles",
    "Taguan",
    "Taipan",
    "Takin",
    "Tamandua mexicana (northern anteater)",
    "Tamarin",
    "Tamarin monkeys",
    "Tamaskan",
    "Tanager",
    "Tang",
    "Tangle web spider",
    "Tangle web spiders",
    "Tanuki",
    "Tapanuli orang-utan",
    "Tapanuli orangutan",
    "Tapir",
    "Tarantula",
    "Tarantula hawk",
    "Tarantula spider",
    "Tarpan",
    "Tarpon",
    "Tarsier",
    "Tasmanian devil",
    "Tasmanian tiger",
    "Tawny eagle",
    "Tawny frogmouth",
    "Tawny owl",
    "Teddy bear hamster",
    "Teddy roosevelt terrier",
    "Tegu",
    "Tegu lizard",
    "Teira batfish",
    "Telescope fish",
    "Tench",
    "Tennessee walking horse",
    "Tenterfield terrier",
    "Termite",
    "Tern",
    "Terrier",
    "Tetra",
    "Texas blind snake",
    "Texas coral snake",
    "Texas garter snake",
    "Texas heeler",
    "Texas indigo snake",
    "Texas night snake",
    "Texas rat snake",
    "Texas spiny lizard",
    "Thai ridgeback",
    "The atlantic wolffish",
    "The bald eagle",
    "The capybara",
    "The cone snail",
    "The eagle owl",
    "The giant squid",
    "The harpy eagle",
    "The leopard",
    "The numbat",
    "The polecat weasel",
    "The porcupine",
    "The puma cat",
    "The raccoon dog",
    "The red wolf",
    "The silvery gibbon",
    "The skunk",
    "The slipper lobster",
    "The spotted hyena",
    "The stink bugs",
    "The vultures",
    "Thomson's gazelle",
    "Thorny devil",
    "Thorny oyster",
    "Thorny woodcock",
    "Thoroughbred",
    "Thoroughbred horse",
    "Thread-winged lacewin",
    "Thresher shark",
    "Thrush",
    "Thylacoleo",
    "Tibetan fox",
    "Tibetan mastiff",
    "Tibetan spaniel",
    "Tibetan terrier",
    "Tick",
    "Ticks",
    "Tiffany",
    "Tiger",
    "Tiger beetle",
    "Tiger moth",
    "Tiger rattlesnake",
    "Tiger salamander",
    "Tiger shark",
    "Tiger snake",
    "Tigress & cubs",
    "Timber rattlesnake",
    "Timber rattlesnake (canebrake rattlesnake)",
    "Tire track eel",
    "Titanoboa",
    "Titi monkeys",
    "Titmouse",
    "Toad",
    "Toad & insect",
    "Toadfish",
    "Toco toucan",
    "Tokay gecko",
    "Torkie",
    "Tortoise",
    "Toucan",
    "Towhee",
    "Toy fox terrier",
    "Toy poodle",
    "Transylvanian hound",
    "Trapdoor spider",
    "Tree frog",
    "Tree kangaroo",
    "Tree snake",
    "Tree swallow",
    "Tree swift",
    "Treecreeper",
    "Treeing tennessee brindle",
    "Treeing walker coonhound",
    "Triceratops",
    "Triggerfish",
    "Trilobite",
    "Tropical fish",
    "Tropicbird",
    "Trout",
    "Trout & char",
    "Trumpeter swan",
    "Tsetse fly",
    "Tuatara",
    "Tuco tuco",
    "Tuna",
    "Tundra swan",
    "Tundra wolf",
    "Tur",
    "Turkey",
    "Turkey vulture",
    "Turkish angora",
    "Turtle",
    "Turtle dove",
    "Turtles",
    "Twig snake",
    "Tyrannosaurus",
    "Uakari",
    "Uganda kob",
    "Uguisu",
    "Uinta chipmunk",
    "Uinta ground squirrel",
    "Uintatherium",
    "Ulysses butterfly",
    "Umbrella bird",
    "Umbrellabird",
    "Unau",
    "Unau (linnaeus's two-toed sloth)",
    "Unicornfish",
    "Upupa",
    "Ural owl",
    "Urchin",
    "Urial",
    "Uromastyx",
    "Urraca",
    "Urutu snake",
    "Utonagan",
    "Vampire bat",
    "Vampire bats",
    "Vampire squid",
    "Vancouver island marmot",
    "Vanga",
    "Vaquita",
    "Variegated squirrel",
    "Veiled chameleon",
    "Velociraptor",
    "Velvet asity",
    "Vendace fish",
    "Venus flytrap",
    "Verreaux’s sifaka",
    "Vervet monkey",
    "Victoria crowned pigeons",
    "Vicuna",
    "Vicuña",
    "Vine snake",
    "Vinegaroon",
    "Viper",
    "Viper shark (dogfish)",
    "Viperfish",
    "Vireo",
    "Virgin islands dwarf gecko",
    "Virginia opossum",
    "Visayan spotted deer",
    "Visayan warty pig",
    "Vizsla",
    "Vlei rat",
    "Volcano rabbit",
    "Vole",
    "Volpino italiano",
    "Vulture",
    "Wahoo",
    "Wahoo fish",
    "Walking catfish",
    "Wall creepers",
    "Wallaby",
    "Wallaby & joey",
    "Walleye fish",
    "Walrus",
    "Wandering albatross",
    "Warthog",
    "Warthogwasps",
    "Wasp",
    "Wasps",
    "Water beetle",
    "Water beetlewaterbuck",
    "Water buffalo",
    "Water deer",
    "Water dragon",
    "Water monitor",
    "Water vole",
    "Waterbuck",
    "Waxwing",
    "Weasel",
    "Weaver",
    "Weaver bird",
    "Weevil beetlemanatee",
    "Weimaraner",
    "Weimardoodle",
    "Wels catfish",
    "Welsh corgi",
    "Welsh terrier",
    "Welsh terriers",
    "West african green monkeys",
    "West african manatee",
    "West highland terrier",
    "West indian manatee",
    "Western blind snake",
    "Western diamondback rattlesnake",
    "Western gorilla",
    "Western green mamba",
    "Western hognose snake",
    "Western lowland gorilla",
    "Western lowland gorillas",
    "Western rat snake",
    "Westiepoo",
    "Whale",
    "Whale shark",
    "Whales",
    "Wheaten terrier",
    "Whimbrel",
    "Whimbrel birds",
    "Whinchat",
    "Whippet",
    "Whiptail lizard",
    "White bengal tiger",
    "White butterfly",
    "White faced capuchin",
    "White ferret / albino ferrets",
    "White hawk",
    "White marlin",
    "White rabbit",
    "White rhino",
    "White rhinoceros",
    "White spoonbill",
    "White stork birds",
    "White tiger",
    "White-clawed crayfish",
    "White-faced capuchin",
    "White-tail deer",
    "White-tailed eagle",
    "Whitefish",
    "Whitetail deer",
    "Whiting",
    "Whoodle",
    "Whooping crane",
    "Wild boar",
    "Wild horse",
    "Wild rabbits",
    "Wild turkey",
    "Wildebeest",
    "Willet",
    "Willow warbler",
    "Winter white russian hamster",
    "Wire fox terrier",
    "Wirehaired pointing griffon",
    "Wolf",
    "Wolf eel",
    "Wolf snake",
    "Wolf spider",
    "Wolffish",
    "Wolverine",
    "Wolves",
    "Wombat",
    "Wood bison",
    "Wood duck",
    "Wood frog",
    "Wood rat",
    "Wood tick",
    "Wood turtle",
    "Woodcock",
    "Woodlouse",
    "Woodlouse spider",
    "Woodpecker",
    "Woodrat",
    "Woolly mammoth",
    "Woolly monkey",
    "Woolly rhinoceros",
    "Worm",
    "Worm snake",
    "Worms",
    "Wrasse",
    "Writing spider",
    "Wrought iron butterflyfish",
    "Wyoming toad",
    "X-ray fish",
    "X-ray tetra",
    "Xantic sargo",
    "Xantus murrelet",
    "Xantus’s hummingbird",
    "Xenarthra",
    "Xenopoecilus",
    "Xenops",
    "Xerus",
    "Xingu river ray",
    "Xolmis",
    "Xoloitzcuintli",
    "Yabby",
    "Yacare caimans",
    "Yak",
    "Yakutian laika",
    "Yarara",
    "Yellow anaconda",
    "Yellow baboon",
    "Yellow cobra",
    "Yellow ground squirrel",
    "Yellow jacket wasp",
    "Yellow mongoose",
    "Yellow sac spider",
    "Yellow spotted lizard",
    "Yellow-backed duiker",
    "Yellow-bellied marmot",
    "Yellow-bellied sea snake",
    "Yellow-bellied weasel",
    "Yellow-eyed penguin",
    "Yellow-footed antechinus",
    "Yellow-footed rock wallaby",
    "Yellow-necked field mouse",
    "Yellow-nosed cotton rat",
    "Yellow-pine chipmunk",
    "Yellow-throated marten",
    "Yellow-winged bat",
    "Yellowfin tuna",
    "Yellowjacket",
    "Yellowtail",
    "Yeti crab",
    "Yoranian",
    "Yorkie bichon",
    "Yorkie-poo",
    "Yorkshire terrier",
    "Yucatan squirrel",
    "Yuma myotis",
    "Zapata wren",
    "Zebra",
    "Zebra butterfly",
    "Zebra duiker",
    "Zebra finch",
    "Zebra mussels",
    "Zebra pleco",
    "Zebra shark",
    "Zebra snake",
    "Zebra spitting cobra",
    "Zebrafish",
    "Zebras",
    "Zebu",
    "Zenaida dove",
    "Zokor",
    "Zone-tailed pigeon",
    "Zonkey",
    "Zorilla",
    "Zorro",
    "Zorse",
    "Zuchon",
]


if __name__ == '__main__':
    print(choice(animals))


