from random import choice

random_statements = [
"Against All Odds",
"Always Be Honest",
"Always Be Yourself",
"Always Remain Neutral",
"Be My Hero",
"Because I Can",
"Believe In Yourself",
"Celebrate Your Victories",
"Change Is Good",
"Do Not Judge",
"Do Not Lie",
"Do Not Be Afraid",
"Do Not Drive Drunk",
"Family Is Forever",
"Forever My Friend",
"Forgive My Sins",
"Get Enough Sleep",
"Go For It",
"God Alone Saves",
"Got Your Back",
"Hearts Can Mend",
"Hold My Hand",
"Hope Trumps All",
"How Are You?",
"Hugs Heal All",
"I Am Kidding",
"I Am Sorry",
"I Do Not Know",
"I Love You",
"I Miss You",
"I Respect You",
"I Trust You",
"I Will Be There",
"Imperfection Is Beauty",
"Keep It Fun",
"Keep It Legal",
"Knowledge Is Power",
"Laughter Is Best",
"Learn From Yesterday",
"Let It Be",
"Let It Go",
"Let Us Be Friends",
"Let Us Just Dance",
"Let Us Just Kiss",
"Let Us Run Away",
"Life Is Life",
"Life Will Not Wait",
"Live Life Daily",
"Love Endures Delay",
"Love Is Everything",
"Make It Happen",
"Marry Me Now",
"Maybe You Are Right",
"Mistakes Make People",
"Never Look Back",
"No Strings Attached",
"Now Or Never",
"Nurture Your Best",
"Only Hope Remains",
"Over And Out",
"Passion Strength Fire",
"Please Forgive Me",
"Please Help Me",
"Protect Your Health",
"Rain Will Fall",
"Ramble On Man",
"Ride Or Die",
"Safe And Sound",
"Save Every Penny",
"Seize The Day",
"Shoot The Moon",
"Speak The Truth",
"Stay The Course",
"Thank You So",
"Thanks So Much",
"This Is Music",
"This Will Pass",
"Time Heals Everything",
"Today Is A Gift",
"Touch My Soul",
"Try Something New",
"Wake Your Dreams",
"Wake Up Your Dreams",
"Where Are You?",
"Where Are You At?",
"Wheres My Head?",
"Who Are You?",
"You Are Kidding",
"You Are Kidding, Right?",
"You Had Time",
"You Had A Hell Of A Time",
]

if __name__ == '__main__':
    print(f"{choice(random_statements)}")
