#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# =============================================================================
# Created Syst: macOS Monterey 12.6 (21G115) Kernel: Darwin 21.6.0
# Created Plat: Python 3.10.8 ('v3.10.8:aaaf517424', 'Oct 11 2022 10:14:40')
# Created By  : jayrizzo
# Created Date: Tue Dec 31 11:10:12 2022 CST
# Last ModDate: Tue Dec 31 21:51:10 2022 CST
# =============================================================================
# Notes:
# =============================================================================
"""Download Youtube Audio by providing the URL."""
import functools  # Reduce - Required for ID3 Header Checks
from os.path import exists as filepathexist
from sys import argv
from os import getcwd
from os.path import dirname
from os.path import join
from os import makedirs
from os.path import expanduser
import PySimpleGUI as sg
from time import sleep
from pyMP3TagEditor import MP3TagYourSong           # Custom Import From This Location
# ========================================================================
# KNOWN ISSUES
# ========================================================================

# ========================================================================
# Research
# ========================================================================
# https://stackoverflow.com/a/58014474/1896134
# https://stackoverflow.com/q/18248200/1896134

# Four Character Imports
# https://pypi.org/project/mutagen/1.45.1/
# https://mutagen.readthedocs.io/en/latest/changelog.html
# https://mutagen.readthedocs.io/en/latest/api/id3_frames.html?highlight=Group%20identification%20registration
#
# ========================================================================
# Load Emoji Characters ==================================================
# ========================================================================
MUSICNOTE = '\U0001F3B5'
THINKINFC = '\U00002795'
CHEQRDFLG = '\U0001F7E2'


class App(object):
    """JayRizzo Youtube Downloader."""
    def __init__(self):
        """JayRizzo Youtube Downloader Initial Launch Setup."""
        super().__init__()
        # ========================================================================
        # ==================== Initialize the SimpleGUI Layout ===================
        # ========================================================================
        self.OS_PATH                = ''
        self.CURRENT_DIR            = dirname(argv[0])
        self.THEME                  = sg.ChangeLookAndFeel('Dark')
        self.OPTION                 = sg.SetOptions (
                                                      background_color = 'Black'
                                                    , element_background_color = 'Grey'
                                                    , text_element_background_color = 'Black'
                                                    , font = ('Arial', 12, 'bold')
                                                    , text_color = 'White'
                                                    , input_text_color = 'White'
                                                    , button_color = (sg.YELLOWS[0], sg.BLUES[1])
                                                    )

        # Set Groups For Layout
        self.row01 = [  sg.T(''                                                                 , expand_x=True, key='-IDTEXT-')]
        self.row02 = [  sg.FileBrowse(f'Select File To View Meta Data {THINKINFC}'              , expand_x=True, key='-ID-')]
        self.row03 = [  sg.B(F'Show Meta {CHEQRDFLG}', button_color=(sg.YELLOWS[0], sg.BLUES[1]), expand_x=True, key='-SHOWMETADATA-'           , size=(20,1))]
        self.row04 = [  sg.T('Title:')     , sg.InputText(''                                    , expand_x=True, key='-TEXT-SONGTITLE-'         , size=(60,1))
                      , sg.T('Duration:')  , sg.InputText(''                                    , expand_x=True, key='-TEXT-SONGDURATIONTIME-'  , size=(5, 1))]
        self.row05 = [  sg.T('Artist:')    , sg.InputText(''                                    , expand_x=True, key='-TEXT-SONGARTIST-'        , size=(60,1))
                      , sg.T('PlayCount:') , sg.InputText(''                                    , expand_x=True, key='-NUMBER-SONGPLAYCOUNT-'   , size=(5, 1))]
        self.row16 = [  sg.T('Album Artist:')     , sg.InputText(''                             , expand_x=True, key='-TEXT-SONGALBUMARTIST-'         , size=(60,1))]
        self.row06 = [  sg.T('Album:')     , sg.InputText(''                                    , expand_x=True, key='-TEXT-SONGALBUM-'         , size=(60,1))]
        self.row07 = [  sg.T('BitRate:')   , sg.InputText(''                                    , expand_x=True, key='-NUMBER-BITRATE-'         , size=(20,1), disabled=True)]
        self.row08 = []
        self.row30 = [ sg.B(f'Save', button_color=(sg.YELLOWS[0], sg.BLUES[1])                  , expand_x=True, key='-SAVEDATA-'               , size=(20,1))]

        # Build Layout
        self.LAYOUT = [
                          self.row01
                        , self.row02
                        , self.row03
                        , self.row04
                        , self.row05
                        , self.row16
                        , self.row06
                        , self.row07
                        , self.row30
                      ]

        # Build Window
        self.WINDOW = sg.Window(F"{MUSICNOTE} JayRizzo's MP3 Meta Data Exposè {MUSICNOTE}"
                                , self.LAYOUT
                                , font = 'Arial 12'
                                , size=(700, 500)
                                , resizable = True
                                , grab_anywhere = False
                                , finalize=True
                                , keep_on_top=True
                                )

    def guiUpdater(self):
        self.SONG = MP3TagYourSong(self.values['-ID-'])
        self.WINDOW['-TEXT-SONGTITLE-'].Update(self.SONG.getSongName())
        self.WINDOW['-TEXT-SONGARTIST-'].Update(self.SONG.getSongArtist())
        self.WINDOW['-TEXT-SONGALBUM-'].Update(self.SONG.getSongAlbum())
        self.WINDOW['-NUMBER-SONGPLAYCOUNT-'].Update(self.SONG.getSongPlayCount())
        self.WINDOW['-TEXT-SONGDURATIONTIME-'].Update(self.SONG.duration_from_seconds(self.SONG.SONGDURATION))
        self.WINDOW['-NUMBER-BITRATE-'].Update(self.SONG.getSongInfoBitrate()[1])
        self.WINDOW['-TEXT-SONGALBUMARTIST-'].Update(self.SONG.getSongAlbumArtist())
        # self.WINDOW['-NUMBER-SONGBPM-'].Update(self.SONG.getSongBPM())
        # self.WINDOW['-NUMBER-SONGDURATIONSEC-'].Update(self.SONG.SongDuration)
        # self.WINDOW['-TEXT-SONGALBUM-'].Update(self.SONG.getSongName())
        print('guiUpdater was called.')
        self.SONG.CreateMissingTag()
        self.SONG.CheckID3Tag()
        self.SONG.convertID3Tags2to3()

    def main(self):
        # Create an self.event loop
        while True:
            self.event, self.values = self.WINDOW.read()
            print(self.event, self.values)
            self.WINDOW['-IDTEXT-'].Update(self.values['-ID-'])

            if self.event == "-SHOWMETADATA-":
                if len(self.values['-ID-']) >= 11:
                    self.guiUpdater()

            if self.event == "-SAVEDATA-":
                    self.SONG = MP3TagYourSong(self.values['-ID-'])
                    self.SONG.setSongTitle(f"{self.values['-TEXT-SONGTITLE-']}")
                    self.SONG.setSongArtist(f"{self.values['-TEXT-SONGARTIST-']}")
                    self.SONG.setSongAlbum(f"{self.values['-TEXT-SONGALBUM-']}")
                    self.SONG.setSongAlbumArtist(f"{self.values['-TEXT-SONGALBUMARTIST-']}")
                    self.SONG.setSongPlayCount(f"{self.values['-NUMBER-SONGPLAYCOUNT-']}")
                    self.guiUpdater()

            if self.event == "-EXITBTN-" or self.event == sg.WIN_CLOSED:
                # END PROGRAM IF USER CLOSES WINDOW
                break

if __name__ == "__main__":
    app = App()
    app.main()


# def Example():
#     with sg.FlexForm('Facebook problem') as form:
#         form_rows = [[sg.Text('Enter your name address and city')],
#                      [sg.Text('Name', size=(15, 1), justification='right'), sg.InputText('Name')],
#                      [sg.Text('Address', size=(15, 1), justification='right'), sg.InputText('Address')],
#                      [sg.Text('City', size=(15, 1), justification='right'), sg.InputText('City')],
#                      [sg.Ok(), sg.Cancel()]]
#         button, (name, address, city) = form.LayoutAndRead(form_rows)
#     if button == 'Ok':
#         sg.MsgBox('You entered', name, address, city)
#     else:
#         sg.MsgBoxError('Cancelled', 'User Cancelled')

# Example()
# ['ALTERNATE_TABLE_AND_TREE_SELECTED_ROW_COLORS',
# 'AddMenuItem',
# 'AddToReturnDictionary',
# 'AddToReturnList',
# 'Any',
# 'B',
# 'BLANK_BASE64',
# 'BLUES',
# 'BM',
# 'BMenu',
# 'BROWSE_FILES_DELIMITER',
# 'BUTTON_DISABLED_MEANS_IGNORE',
# 'BUTTON_TYPE_BROWSE_FILE',
# 'BUTTON_TYPE_BROWSE_FILES',
# 'BUTTON_TYPE_BROWSE_FOLDER',
# 'BUTTON_TYPE_CALENDAR_CHOOSER',
# 'BUTTON_TYPE_CLOSES_WIN',
# 'BUTTON_TYPE_CLOSES_WIN_ONLY',
# 'BUTTON_TYPE_COLOR_CHOOSER',
# 'BUTTON_TYPE_READ_FORM',
# 'BUTTON_TYPE_REALTIME',
# 'BUTTON_TYPE_SAVEAS_FILE',
# 'BUTTON_TYPE_SHOW_DEBUGGER',
# 'Btn',
# 'Button',
# 'ButtonMenu',
# 'CB',
# 'CBox',
# 'CButton',
# 'COLOR_SCHEME',
# 'COLOR_SYSTEM_DEFAULT',
# 'CPRINT_DESTINATION_MULTILINE_ELMENT_KEY',
# 'CPRINT_DESTINATION_WINDOW',
# 'CURRENT_LOOK_AND_FEEL',
# 'CUSTOM_MENUBAR_METADATA_MARKER',
# 'CUSTOM_TITLEBAR_BACKGROUND_COLOR',
# 'CUSTOM_TITLEBAR_FONT',
# 'CUSTOM_TITLEBAR_ICON',
# 'CUSTOM_TITLEBAR_TEXT_COLOR',
# 'CalendarButton',
# 'Cancel',
# 'Canvas',
# 'ChangeLookAndFeel',
# 'Check',
# 'Checkbox',
# 'CloseButton',
# 'Col',
# 'ColorChooserButton',
# 'Column',
# 'Combo',
# 'ConvertArgsToSingleString',
# 'DD',
# 'DEBUGGER_POPOUT_THEME',
# 'DEBUGGER_VARIABLE_DETAILS_FONT',
# 'DEFAULT_ALPHA_CHANNEL',
# 'DEFAULT_AUTOCLOSE_TIME',
# 'DEFAULT_AUTOSIZE_BUTTONS',
# 'DEFAULT_AUTOSIZE_TEXT',
# 'DEFAULT_BACKGROUND_COLOR',
# 'DEFAULT_BASE64_ICON',
# 'DEFAULT_BASE64_ICON_16_BY_16',
# 'DEFAULT_BASE64_LOADING_GIF',
# 'DEFAULT_BORDER_WIDTH',
# 'DEFAULT_BUTTON_COLOR',
# 'DEFAULT_BUTTON_ELEMENT_SIZE',
# 'DEFAULT_DEBUG_WINDOW_SIZE',
# 'DEFAULT_ELEMENT_BACKGROUND_COLOR',
# 'DEFAULT_ELEMENT_PADDING',
# 'DEFAULT_ELEMENT_SIZE',
# 'DEFAULT_ELEMENT_TEXT_COLOR',
# 'DEFAULT_ERROR_BUTTON_COLOR',
# 'DEFAULT_FONT',
# 'DEFAULT_FRAME_RELIEF',
# 'DEFAULT_HIDE_WINDOW_WHEN_CREATING',
# 'DEFAULT_INPUT_ELEMENTS_COLOR',
# 'DEFAULT_INPUT_TEXT_COLOR',
# 'DEFAULT_KEEP_ON_TOP',
# 'DEFAULT_LISTBOX_SELECT_MODE',
# 'DEFAULT_MARGINS',
# 'DEFAULT_METER_ORIENTATION',
# 'DEFAULT_MODAL_WINDOWS_ENABLED',
# 'DEFAULT_MODAL_WINDOWS_FORCED',
# 'DEFAULT_PROGRESS_BAR_BORDER_WIDTH',
# 'DEFAULT_PROGRESS_BAR_COLOR',
# 'DEFAULT_PROGRESS_BAR_COLOR_OFFICIAL',
# 'DEFAULT_PROGRESS_BAR_COMPUTE',
# 'DEFAULT_PROGRESS_BAR_RELIEF',
# 'DEFAULT_PROGRESS_BAR_SIZE',
# 'DEFAULT_PROGRESS_BAR_STYLE',
# 'DEFAULT_SCALING',
# 'DEFAULT_SCROLLBAR_COLOR',
# 'DEFAULT_SLIDER_BORDER_WIDTH',
# 'DEFAULT_SLIDER_ORIENTATION',
# 'DEFAULT_SLIDER_RELIEF',
# 'DEFAULT_TABLE_SELECT_MODE',
# 'DEFAULT_TEXT_COLOR',
# 'DEFAULT_TEXT_ELEMENT_BACKGROUND_COLOR',
# 'DEFAULT_TEXT_JUSTIFICATION',
# 'DEFAULT_TOOLTIP_OFFSET',
# 'DEFAULT_TOOLTIP_TIME',
# 'DEFAULT_TTK_PART_MAPPING_DICT',
# 'DEFAULT_TTK_THEME',
# 'DEFAULT_USER_SETTINGS_LINUX_PATH',
# 'DEFAULT_USER_SETTINGS_MAC_PATH',
# 'DEFAULT_USER_SETTINGS_PATH',
# 'DEFAULT_USER_SETTINGS_PYSIMPLEGUI_FILENAME',
# 'DEFAULT_USER_SETTINGS_PYSIMPLEGUI_PATH',
# 'DEFAULT_USER_SETTINGS_REPLIT_PATH',
# 'DEFAULT_USER_SETTINGS_TRINKET_PATH',
# 'DEFAULT_USER_SETTINGS_UNKNOWN_OS_PATH',
# 'DEFAULT_USER_SETTINGS_WIN_PATH',
# 'DEFAULT_USE_BUTTON_SHORTCUTS',
# 'DEFAULT_WINDOW_ICON',
# 'DEFAULT_WINDOW_LOCATION',
# 'DEFAULT_WINDOW_SNAPSHOT_KEY',
# 'DEFAULT_WINDOW_SNAPSHOT_KEY_CODE',
# 'Debug',
# 'DecodeRadioRowCol',
# 'Dict',
# 'Drop',
# 'DropDown',
# 'DummyButton',
# 'ELEM_TYPE_BLANK',
# 'ELEM_TYPE_BUTTON',
# 'ELEM_TYPE_BUTTONMENU',
# 'ELEM_TYPE_CANVAS',
# 'ELEM_TYPE_COLUMN',
# 'ELEM_TYPE_ERROR',
# 'ELEM_TYPE_FRAME',
# 'ELEM_TYPE_GRAPH',
# 'ELEM_TYPE_IMAGE',
# 'ELEM_TYPE_INPUT_CHECKBOX',
# 'ELEM_TYPE_INPUT_COMBO',
# 'ELEM_TYPE_INPUT_LISTBOX',
# 'ELEM_TYPE_INPUT_MULTILINE',
# 'ELEM_TYPE_INPUT_OPTION_MENU',
# 'ELEM_TYPE_INPUT_RADIO',
# 'ELEM_TYPE_INPUT_SLIDER',
# 'ELEM_TYPE_INPUT_SPIN',
# 'ELEM_TYPE_INPUT_TEXT',
# 'ELEM_TYPE_MENUBAR',
# 'ELEM_TYPE_OUTPUT',
# 'ELEM_TYPE_PANE',
# 'ELEM_TYPE_PROGRESS_BAR',
# 'ELEM_TYPE_SEPARATOR',
# 'ELEM_TYPE_SIZEGRIP',
# 'ELEM_TYPE_STATUSBAR',
# 'ELEM_TYPE_TAB',
# 'ELEM_TYPE_TABLE',
# 'ELEM_TYPE_TAB_GROUP',
# 'ELEM_TYPE_TEXT',
# 'ELEM_TYPE_TITLEBAR',
# 'ELEM_TYPE_TREE',
# 'EMOJI_BASE64_BLANK_STARE',
# 'EMOJI_BASE64_CLAP',
# 'EMOJI_BASE64_COOL',
# 'EMOJI_BASE64_CRAZY',
# 'EMOJI_BASE64_CRY',
# 'EMOJI_BASE64_DEAD',
# 'EMOJI_BASE64_DEPRESSED',
# 'EMOJI_BASE64_DREAMING',
# 'EMOJI_BASE64_EYE_ROLL',
# 'EMOJI_BASE64_FACEPALM',
# 'EMOJI_BASE64_FINGERS_CROSSED',
# 'EMOJI_BASE64_FRUSTRATED',
# 'EMOJI_BASE64_GLASSES',
# 'EMOJI_BASE64_GOLD_STAR',
# 'EMOJI_BASE64_GUESS',
# 'EMOJI_BASE64_HAPPY_BIG_SMILE',
# 'EMOJI_BASE64_HAPPY_CONTENT',
# 'EMOJI_BASE64_HAPPY_GASP',
# 'EMOJI_BASE64_HAPPY_HEARTS',
# 'EMOJI_BASE64_HAPPY_IDEA',
# 'EMOJI_BASE64_HAPPY_JOY',
# 'EMOJI_BASE64_HAPPY_LAUGH',
# 'EMOJI_BASE64_HAPPY_LIST',
# 'EMOJI_BASE64_HAPPY_RELIEF',
# 'EMOJI_BASE64_HAPPY_STARE',
# 'EMOJI_BASE64_HAPPY_THUMBS_UP',
# 'EMOJI_BASE64_HAPPY_WINK',
# 'EMOJI_BASE64_HEAD_EXPLODE',
# 'EMOJI_BASE64_HONEST',
# 'EMOJI_BASE64_ILL',
# 'EMOJI_BASE64_ILL2',
# 'EMOJI_BASE64_JASON',
# 'EMOJI_BASE64_KEY',
# 'EMOJI_BASE64_LAPTOP',
# 'EMOJI_BASE64_LIST',
# 'EMOJI_BASE64_MASK',
# 'EMOJI_BASE64_MIKE',
# 'EMOJI_BASE64_NOTUNDERSTANDING',
# 'EMOJI_BASE64_NO_HEAR',
# 'EMOJI_BASE64_NO_SEE',
# 'EMOJI_BASE64_NO_SPEAK',
# 'EMOJI_BASE64_OK',
# 'EMOJI_BASE64_PARTY',
# 'EMOJI_BASE64_PONDER',
# 'EMOJI_BASE64_PRAY',
# 'EMOJI_BASE64_QUESTION',
# 'EMOJI_BASE64_RAINEDON',
# 'EMOJI_BASE64_READING',
# 'EMOJI_BASE64_SAD',
# 'EMOJI_BASE64_SAD_LIST',
# 'EMOJI_BASE64_SALUTE',
# 'EMOJI_BASE64_SANTA',
# 'EMOJI_BASE64_SCREAM',
# 'EMOJI_BASE64_SEARCH',
# 'EMOJI_BASE64_SKEPTIC',
# 'EMOJI_BASE64_SKEPTICAL',
# 'EMOJI_BASE64_SLEEPING',
# 'EMOJI_BASE64_SMIRKING',
# 'EMOJI_BASE64_SUPERHERO',
# 'EMOJI_BASE64_TEAR',
# 'EMOJI_BASE64_THINK',
# 'EMOJI_BASE64_UPSIDE_DOWN',
# 'EMOJI_BASE64_WARNING',
# 'EMOJI_BASE64_WARNING2',
# 'EMOJI_BASE64_WAVE',
# 'EMOJI_BASE64_WEARY',
# 'EMOJI_BASE64_WIZARD',
# 'EMOJI_BASE64_YIKES',
# 'EMOJI_BASE64_ZIPPED_SHUT',
# 'ENABLE_MAC_ALPHA_99_PATCH',
# 'ENABLE_MAC_DISABLE_GRAB_ANYWHERE_WITH_TITLEBAR',
# 'ENABLE_MAC_MODAL_DISABLE_PATCH',
# 'ENABLE_MAC_NOTITLEBAR_PATCH',
# 'ENABLE_TK_WINDOWS',
# 'ENABLE_TREEVIEW_869_PATCH',
# 'EVENT_SYSTEM_TRAY_ICON_ACTIVATED',
# 'EVENT_SYSTEM_TRAY_ICON_DOUBLE_CLICKED',
# 'EVENT_SYSTEM_TRAY_MESSAGE_CLICKED',
# 'EVENT_TIMEOUT',
# 'EasyPrint',
# 'EasyPrintClose',
# 'Element',
# 'EncodeRadioRowCol',
# 'ErrorElement',
# 'Exit',
# 'FILE_TYPES_ALL_FILES',
# 'FileBrowse',
# 'FileSaveAs',
# 'FilesBrowse',
# 'FillFormWithValues',
# 'FlexForm',
# 'FolderBrowse',
# 'Fr',
# 'Frame',
# 'G',
# 'GRAB_ANYWHERE_IGNORE_THESE_WIDGETS',
# 'GREENS',
# 'GREEN_CHECK_BASE64',
# 'GetComplimentaryHex',
# 'Graph',
# 'HEART_3D_BASE64',
# 'HEART_FLAT_BASE64',
# 'HSep',
# 'HSeparator',
# 'Help',
# 'HorizontalSeparator',
# 'I',
# 'ICON_BUY_ME_A_COFFEE',
# 'Im',
# 'Image',
# 'In',
# 'InitializeResults',
# 'Input',
# 'InputCombo',
# 'InputOptionMenu',
# 'InputText',
# 'LB',
# 'LBox',
# 'LISTBOX_SELECT_MODE_BROWSE',
# 'LISTBOX_SELECT_MODE_EXTENDED',
# 'LISTBOX_SELECT_MODE_MULTIPLE',
# 'LISTBOX_SELECT_MODE_SINGLE',
# 'LOOK_AND_FEEL_TABLE',
# 'List',
# 'ListOfLookAndFeelValues',
# 'Listbox',
# 'MAC_PATCH_DICT',
# 'MAX_LINES_PER_RESULT_FLOATING',
# 'MAX_LINES_PER_RESULT_MAIN',
# 'MAX_SCROLLED_TEXT_BOX_HEIGHT',
# 'MAX_TIMEIT_COUNT',
# 'MENU_DISABLED_CHARACTER',
# 'MENU_KEY_SEPARATOR',
# 'MENU_RIGHT_CLICK_DISABLED',
# 'MENU_RIGHT_CLICK_EDITME_EXIT',
# 'MENU_RIGHT_CLICK_EDITME_VER_EXIT',
# 'MENU_RIGHT_CLICK_EDITME_VER_LOC_EXIT',
# 'MENU_RIGHT_CLICK_EDITME_VER_SETTINGS_EXIT',
# 'MENU_RIGHT_CLICK_EXIT',
# 'MENU_SEPARATOR_LINE',
# 'MENU_SHORTCUT_CHARACTER',
# 'MESSAGE_BOX_LINE_WIDTH',
# 'METER_OK',
# 'METER_REASON_CANCELLED',
# 'METER_REASON_CLOSED',
# 'METER_REASON_REACHED_MAX',
# 'METER_STOPPED',
# 'ML',
# 'MLine',
# 'Menu',
# 'MenuBar',
# 'Menubar',
# 'MenubarCustom',
# 'MsgBox',
# 'Multiline',
# 'NICE_BUTTON_COLORS',
# 'NUM_AUTO_WATCH',
# 'No',
# 'OFFICIAL_PYSIMPLEGUI_BUTTON_COLOR',
# 'OFFICIAL_PYSIMPLEGUI_THEME',
# 'OK',
# 'OLD_TABLE_TREE_SELECTED_ROW_COLORS',
# 'ObjToString',
# 'ObjToStringSingleObj',
# 'Ok',
# 'OneLineProgressMeter',
# 'OneLineProgressMeterCancel',
# 'Open',
# 'OptionMenu',
# 'Optional',
# 'Output',
# 'P',
# 'PBar',
# 'POPOUT_WINDOW_FONT',
# 'POPUP_BUTTONS_CANCELLED',
# 'POPUP_BUTTONS_ERROR',
# 'POPUP_BUTTONS_NO_BUTTONS',
# 'POPUP_BUTTONS_OK',
# 'POPUP_BUTTONS_OK_CANCEL',
# 'POPUP_BUTTONS_YES_NO',
# 'PSG_DEBUGGER_LOGO',
# 'PSG_THEME_PART_BACKGROUND',
# 'PSG_THEME_PART_BUTTON_BACKGROUND',
# 'PSG_THEME_PART_BUTTON_TEXT',
# 'PSG_THEME_PART_INPUT_BACKGROUND',
# 'PSG_THEME_PART_INPUT_TEXT',
# 'PSG_THEME_PART_LIST',
# 'PSG_THEME_PART_SLIDER',
# 'PSG_THEME_PART_TEXT',
# 'PURPLES',
# 'PYTHON_COLORED_HEARTS_BASE64',
# 'PackFormIntoFrame',
# 'Pane',
# 'Popup',
# 'PopupAnimated',
# 'PopupAnnoying',
# 'PopupAutoClose',
# 'PopupCancel',
# 'PopupError',
# 'PopupGetFile',
# 'PopupGetFolder',
# 'PopupGetText',
# 'PopupNoBorder',
# 'PopupNoButtons',
# 'PopupNoFrame',
# 'PopupNoTitlebar',
# 'PopupNoWait',
# 'PopupNonBlocking',
# 'PopupOK',
# 'PopupOKCancel',
# 'PopupQuick',
# 'PopupQuickMessage',
# 'PopupScrolled',
# 'PopupTimed',
# 'PopupYesNo',
# 'Print',
# 'PrintClose',
# 'Prog',
# 'Progress',
# 'ProgressBar',
# 'Push',
# 'PySimpleGUI',
# 'QuickMeter',
# 'Quit',
# 'R',
# 'RButton',
# 'RED_X_BASE64',
# 'RELIEF_FLAT',
# 'RELIEF_GROOVE',
# 'RELIEF_LIST',
# 'RELIEF_RAISED',
# 'RELIEF_RIDGE',
# 'RELIEF_SOLID',
# 'RELIEF_SUNKEN',
# 'RGB',
# 'Rad',
# 'Radio',
# 'ReadButton',
# 'ReadFormButton',
# 'RealtimeButton',
# 'SBar',
# 'SELECT_MODE_BROWSE',
# 'SELECT_MODE_EXTENDED',
# 'SELECT_MODE_MULTIPLE',
# 'SELECT_MODE_SINGLE',
# 'SGrip',
# 'SUPPRESS_ERROR_POPUPS',
# 'SUPPRESS_KEY_GUESSING',
# 'SUPPRESS_RAISE_KEY_ERRORS',
# 'SUPPRESS_WIDGET_NOT_FINALIZED_WARNINGS',
# 'SYMBOL_BALLOT_CHECK',
# 'SYMBOL_BALLOT_X',
# 'SYMBOL_BULLET',
# 'SYMBOL_CHECK',
# 'SYMBOL_CHECK_SMALL',
# 'SYMBOL_CIRCLE',
# 'SYMBOL_CIRCLE_OUTLINE',
# 'SYMBOL_DOWN',
# 'SYMBOL_DOWN_ARROWHEAD',
# 'SYMBOL_LEFT',
# 'SYMBOL_LEFT_ARROWHEAD',
# 'SYMBOL_LEFT_DOUBLE',
# 'SYMBOL_RIGHT',
# 'SYMBOL_RIGHT_ARROWHEAD',
# 'SYMBOL_RIGHT_DOUBLE',
# 'SYMBOL_SQUARE',
# 'SYMBOL_TITLEBAR_CLOSE',
# 'SYMBOL_TITLEBAR_MAXIMIZE',
# 'SYMBOL_TITLEBAR_MINIMIZE',
# 'SYMBOL_UP',
# 'SYMBOL_UP_ARROWHEAD',
# 'SYMBOL_X',
# 'SYMBOL_X_SMALL',
# 'SYSTEM_TRAY_MESSAGE_DISPLAY_DURATION_IN_MILLISECONDS',
# 'SYSTEM_TRAY_MESSAGE_FADE_IN_DURATION',
# 'SYSTEM_TRAY_MESSAGE_ICON_CRITICAL',
# 'SYSTEM_TRAY_MESSAGE_ICON_INFORMATION',
# 'SYSTEM_TRAY_MESSAGE_ICON_NOICON',
# 'SYSTEM_TRAY_MESSAGE_ICON_WARNING',
# 'SYSTEM_TRAY_MESSAGE_MAX_LINE_LENGTH',
# 'SYSTEM_TRAY_MESSAGE_TEXT_COLOR',
# 'SYSTEM_TRAY_MESSAGE_WIN_COLOR',
# 'SYSTEM_TRAY_WIN_MARGINS',
# 'Save',
# 'SaveAs',
# 'ScrolledTextBox',
# 'SetGlobalIcon',
# 'SetOptions',
# 'SimpleButton',
# 'Sizegrip',
# 'Sizer',
# 'Sl',
# 'Slider',
# 'Sp',
# 'Spin',
# 'StartupTK',
# 'StatusBar',
# 'Stretch',
# 'Submit',
# 'SupportsAbs',
# 'SystemTray',
# 'T',
# 'TABLE_CLICKED_INDICATOR',
# 'TABLE_SELECT_MODE_BROWSE',
# 'TABLE_SELECT_MODE_EXTENDED',
# 'TABLE_SELECT_MODE_NONE',
# 'TAB_LOCATION_BOTTOM',
# 'TAB_LOCATION_BOTTOM_LEFT',
# 'TAB_LOCATION_BOTTOM_RIGHT',
# 'TAB_LOCATION_LEFT',
# 'TAB_LOCATION_LEFT_BOTTOM',
# 'TAB_LOCATION_LEFT_TOP',
# 'TAB_LOCATION_RIGHT',
# 'TAB_LOCATION_RIGHT_BOTTOM',
# 'TAB_LOCATION_RIGHT_TOP',
# 'TAB_LOCATION_TOP',
# 'TAB_LOCATION_TOP_LEFT',
# 'TAB_LOCATION_TOP_RIGHT',
# 'TANS',
# 'TEXT_LOCATION_BOTTOM',
# 'TEXT_LOCATION_BOTTOM_LEFT',
# 'TEXT_LOCATION_BOTTOM_RIGHT',
# 'TEXT_LOCATION_CENTER',
# 'TEXT_LOCATION_LEFT',
# 'TEXT_LOCATION_RIGHT',
# 'TEXT_LOCATION_TOP',
# 'TEXT_LOCATION_TOP_LEFT',
# 'TEXT_LOCATION_TOP_RIGHT',
# 'THEME_ALT',
# 'THEME_CLAM',
# 'THEME_CLASSIC',
# 'THEME_DEFAULT',
# 'THEME_VISTA',
# 'THEME_WINNATIVE',
# 'THEME_XPNATIVE',
# 'TIMEOUT_EVENT',
# 'TIMEOUT_KEY',
# 'TITLEBAR_CLOSE_KEY',
# 'TITLEBAR_DO_NOT_USE_AN_ICON',
# 'TITLEBAR_IMAGE_KEY',
# 'TITLEBAR_MAXIMIZE_KEY',
# 'TITLEBAR_METADATA_MARKER',
# 'TITLEBAR_MINIMIZE_KEY',
# 'TITLEBAR_TEXT_KEY',
# 'TITLE_LOCATION_BOTTOM',
# 'TITLE_LOCATION_BOTTOM_LEFT',
# 'TITLE_LOCATION_BOTTOM_RIGHT',
# 'TITLE_LOCATION_LEFT',
# 'TITLE_LOCATION_RIGHT',
# 'TITLE_LOCATION_TOP',
# 'TITLE_LOCATION_TOP_LEFT',
# 'TITLE_LOCATION_TOP_RIGHT',
# 'TKCalendar',
# 'TKINTER_CURSORS',
# 'TKProgressBar',
# 'TOOLTIP_BACKGROUND_COLOR',
# 'TOOLTIP_FONT',
# 'TRANSPARENT_BUTTON',
# 'TTKPartOverrides',
# 'TTK_SCROLLBAR_PART_ARROW_BUTTON_ARROW_COLOR',
# 'TTK_SCROLLBAR_PART_ARROW_WIDTH',
# 'TTK_SCROLLBAR_PART_BACKGROUND_COLOR',
# 'TTK_SCROLLBAR_PART_FRAME_COLOR',
# 'TTK_SCROLLBAR_PART_LIST',
# 'TTK_SCROLLBAR_PART_RELIEF',
# 'TTK_SCROLLBAR_PART_SCROLL_WIDTH',
# 'TTK_SCROLLBAR_PART_THEME_BASED_LIST',
# 'TTK_SCROLLBAR_PART_TROUGH_COLOR',
# 'Tab',
# 'TabGroup',
# 'Table',
# 'Text',
# 'ThisRow',
# 'TimerStart',
# 'TimerStop',
# 'Titlebar',
# 'TkFixedFrame',
# 'TkScrollableFrame',
# 'ToolTip',
# 'Tree',
# 'TreeData',
# 'Tuple',
# 'Txt',
# 'UDEMY_ICON',
# 'USE_CUSTOM_TITLEBAR',
# 'USE_TTK_BUTTONS',
# 'Union',
# 'UserSettings',
# 'VP',
# 'VPush',
# 'VSep',
# 'VSeparator',
# 'VSeperator',
# 'VStretch',
# 'VarHolder',
# 'VerticalSeparator',
# 'WARN_DUPLICATE_BUTTON_KEY_ERRORS',
# 'WIDTH_LOCALS',
# 'WIDTH_RESULTS',
# 'WIDTH_VARIABLES',
# 'WIDTH_WATCHER_RESULTS',
# 'WIDTH_WATCHER_VARIABLES',
# 'WINDOW_CLOSED',
# 'WINDOW_CLOSE_ATTEMPTED_EVENT',
# 'WINDOW_CONFIG_EVENT',
# 'WIN_CLOSED',
# 'WIN_CLOSE_ATTEMPTED_EVENT',
# 'WIN_X_EVENT',
# 'WRITE_ONLY_KEY',
# 'Window',
# 'YELLOWS',
# 'Yes',
# '__builtins__',
# '__cached__',
# '__doc__',
# '__file__',
# '__loader__',
# '__name__',
# '__package__',
# '__path__',
# '__spec__',
# '__version__',
# 'askcolor',
# 'button_color_to_tuple',
# 'calendar',
# 'change_look_and_feel',
# 'clipboard_get',
# 'clipboard_set',
# 'configparser',
# 'convert_args_to_single_string',
# 'copy',
# 'cprint',
# 'cprint_set_output_destination',
# 'ctypes',
# 'datetime',
# 'difflib',
# 'easy_print',
# 'easy_print_close',
# 'eprint',
# 'execute_command_subprocess',
# 'execute_editor',
# 'execute_file_explorer',
# 'execute_find_callers_filename',
# 'execute_get_results',
# 'execute_py_file',
# 'execute_py_get_interpreter',
# 'execute_subprocess_still_running',
# 'fabs',
# 'filedialog',
# 'fill_form_with_values',
# 'floor',
# 'framework_version',
# 'g_time_delta',
# 'g_time_end',
# 'g_time_start',
# 'get_complimentary_hex',
# 'get_versions',
# 'hh',
# 'inspect',
# 'itertools',
# 'json',
# 'list_of_look_and_feel_values',
# 'main',
# 'main_get_debug_data',
# 'main_global_get_screen_snapshot_symcode',
# 'main_global_pysimplegui_settings',
# 'main_global_pysimplegui_settings_erase',
# 'main_mac_feature_control',
# 'main_open_github_issue',
# 'main_sdk_help',
# 'main_upgrade_from_github',
# 'name',
# 'obj_to_string',
# 'obj_to_string_single_obj',
# 'one_line_progress_meter',
# 'one_line_progress_meter_cancel',
# 'os',
# 'pickle',
# 'pil_import_attempted',
# 'pil_imported',
# 'pin',
# 'platform',
# 'popup',
# 'popup_animated',
# 'popup_annoying',
# 'popup_auto_close',
# 'popup_cancel',
# 'popup_error',
# 'popup_error_with_traceback',
# 'popup_get_date',
# 'popup_get_file',
# 'popup_get_folder',
# 'popup_get_text',
# 'popup_menu',
# 'popup_no_border',
# 'popup_no_buttons',
# 'popup_no_frame',
# 'popup_no_titlebar',
# 'popup_no_wait',
# 'popup_non_blocking',
# 'popup_notify',
# 'popup_ok',
# 'popup_ok_cancel',
# 'popup_quick',
# 'popup_quick_message',
# 'popup_scrolled',
# 'popup_timed',
# 'popup_yes_no',
# 'port',
# 'pprint',
# 'preview_all_look_and_feel_themes',
# 'pydoc',
# 'pysimplegui_user_settings',
# 'queue',
# 'random',
# 're',
# 'read_all_windows',
# 'read_last_line',
# 'red_x',
# 'request',
# 'rgb',
# 'running_linux',
# 'running_mac',
# 'running_replit',
# 'running_trinket',
# 'running_windows',
# 'scheck_hh',
# 'sdk_help',
# 'set_global_icon',
# 'set_options',
# 'sgprint',
# 'sgprint_close',
# 'shell_with_animation',
# 'show_debugger_popout_window',
# 'show_debugger_window',
# 'socket',
# 'sprint',
# 'subprocess',
# 'sys',
# 'tclversion_detailed',
# 'tempfile',
# 'test',
# 'textwrap',
# 'theme',
# 'theme_add_new',
# 'theme_background_color',
# 'theme_border_width',
# 'theme_button_color',
# 'theme_button_color_background',
# 'theme_button_color_text',
# 'theme_element_background_color',
# 'theme_element_text_color',
# 'theme_global',
# 'theme_input_background_color',
# 'theme_input_text_color',
# 'theme_list',
# 'theme_previewer',
# 'theme_previewer_swatches',
# 'theme_progress_bar_border_width',
# 'theme_progress_bar_color',
# 'theme_slider_border_width',
# 'theme_slider_color',
# 'theme_text_color',
# 'theme_text_element_background_color',
# 'theme_use_custom_titlebar',
# 'threading',
# 'time',
# 'timer_start',
# 'timer_stop',
# 'tk',
# 'tkinter',
# 'tkinter_keysyms',
# 'traceback',
# 'ttk',
# 'ttk_part_mapping_dict',
# 'ttk_part_overrides_from_options',
# 'ttk_theme_in_use',
# 'urllib',
# 'user_settings',
# 'user_settings_delete_entry',
# 'user_settings_delete_filename',
# 'user_settings_file_exists',
# 'user_settings_filename',
# 'user_settings_get_entry',
# 'user_settings_load',
# 'user_settings_object',
# 'user_settings_save',
# 'user_settings_set_entry',
# 'user_settings_silent_on_error',
# 'user_settings_write_new_dictionary',
# 'uuid4',
# 'vbottom',
# 'vcenter',
# 'ver',
# 'version',
# 'vtop',
# 'warnings',
# 'webbrowser',
# 'webbrowser_available',
# 'wraps']
